<?php

/**
 * @file
 */

include_once 'tours.features.inc';

/**
 * Update the tours_get_tour_types function if modifying the tour types.
 */
define ('TOURS_SINGLE_DAY', 'single_day_tour');
define ('TOURS_SINGLE_DAY_SLOT', 'single_day_tour_slot');
define ('TOURS_PRIVATE_SINGLE_DAY_SLOT', 'private_single_day_tour_slot');
define ('TOURS_MULTI_DAY', 'multi_day_tour');

define ('ROOMS_PART_BOOKED', 4);


/**
 * Drupal hooks.
 */

/**
 * Implements hook_menu().
 */
function tours_menu() {
  $items['tours_availability_reference/autocomplete/%/%/%'] = array(
    'page callback' => 'tours_availability_reference_autocomplete',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('reference booking unit availability'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function tours_theme() {
  return array(
    'tours_availability_field_calendar' => array(
      'render element' => 'tours_availability_field_calendar',
      'template' => 'tours_availability_field_calendar',
    ),
    'tours_availability_single_day' => array(
      'render element' => 'tours_availability_single_day',
      'template' => 'tours_availability_single_day',
    ),
  );
}

/**
 * hook_entity_presave().
 */
function tours_entity_presave($entity, $type) {
  if ($type == 'rooms_unit') {
    if ($entity->type == TOURS_SINGLE_DAY) {
      // Single-Day Tour Slot
      if (isset($entity->field_daily_slot[LANGUAGE_NONE])) {
        foreach ($entity->field_daily_slot[LANGUAGE_NONE] as $slot_id) {
          $slot = rooms_unit_load($slot_id['target_id']);

          // Base price of the Single-Day Tour Slot is the same as the Single-Day Tour.
          $slot->base_price = $entity->base_price;

          // The Title of the Single-Day Tour Slot is the same Title as the Single-Day Tour Bookable Unit
          // it is associated with + the start and end time of the tour.
          if ($slot->name == '') {
            $time_format = array(
              'separator' => ':',
              'period_separator' => '',
              'period' => 'a',
              'hour' => 'g',
              'minute' => 'i'
            );

            $start_time = timefield_integer_to_time($time_format, $slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value']);

            $end_time = timefield_integer_to_time($time_format, $slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value2']);

            $slot->name = $entity->name . ' (' . $start_time . ' - ' . $end_time . ')';
          }

          rooms_unit_save($slot);
        }
      }

      // Private Single-Day Tour Slot
      if (isset($entity->field_private_daily_slot[LANGUAGE_NONE])) {
        foreach ($entity->field_private_daily_slot[LANGUAGE_NONE] as $slot_id) {
          $slot = rooms_unit_load($slot_id['target_id']);

          // Base price of the Single-Day Tour Slot is the same as the Single-Day Tour.
          $slot->base_price = $entity->base_price;

          // The Title of the Single-Day Tour Slot is the same Title as the Single-Day Tour Bookable Unit
          // it is associated with + the start and end time of the tour.
          if ($slot->name == '') {
            $time_format = array(
              'separator' => ':',
              'period_separator' => '',
              'period' => 'a',
              'hour' => 'g',
              'minute' => 'i'
            );

            $start_time = timefield_integer_to_time($time_format, $slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value']);

            $end_time = timefield_integer_to_time($time_format, $slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value2']);

            $slot->name = $entity->name . ' (' . $start_time . ' - ' . $end_time . ') - Private tour';
          }

          rooms_unit_save($slot);
        }
      }
    }
    elseif ($entity->type == TOURS_SINGLE_DAY_SLOT || $entity->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
      $entity->default_state = ROOMS_NOT_AVAILABLE;
    }
  }
}

/**
 * Implements hook_field_info().
 */
function tours_field_info() {
  return array(
    'tours_availability_reference' => array(
      'label' => t('Tours Availability Reference'),
      'description' => t('Display availability information embedded from other fieldable content.'),
      'settings' => array(
        'referenceable_unit_types' => array(),
      ),
      'default_widget' => 'tours_availability_reference_autocomplete',
      'default_formatter' => 'tours_multiday_availability_reference_default',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function tours_field_is_empty($item, $field) {
  return empty($item['unit_id']);
}

/**
 * Implements hook_field_formatter_info().
 */
function tours_field_formatter_info() {
  $ret = array(
    'tours_multiday_availability_reference_default' => array(
      'label' => t('Multi-day Availability Calendar'),
      'description' => t('Displays availability information on a calendar.'),
      'field types' => array('tours_availability_reference', 'entityreference'),
      'settings' => array('book_now' => '1', 'enquire_about' => '1'),
    ),
    'tours_singleday_availability_reference_default' => array(
      'label' => t('Single-day Availability Calendar'),
      'description' => t('Displays availability information on a calendar.'),
      'field types' => array('tours_availability_reference', 'entityreference'),
      'settings' => array('enquire_about' => '1', 'display_calendar' => '0'),
    ),
  );
  return $ret;
}

/**
 * Implements hook_field_formatter_prepare_view().
 */
function tours_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {
  if ($field['type'] == 'entityreference') {
    entityreference_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items, $displays);
  }
}

/**
 * Implements hook_field_formatter_view().
 *
 * @todo parametrize date range
 */
function tours_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $booking_ids = array();
  $element = array();

  switch ($display['type']) {
    case 'tours_multiday_availability_reference_default':

      $unit_names = array();
      $unit_ids = array();
      foreach ($items as $delta => $item) {
        if ($field['type'] == 'entityreference') {
          if (empty($item['access'])) {
            continue;
          }
          $unit = ($item['entity']);
        }
        else {
          $unit = rooms_unit_load($item['unit_id']);
        }

        if ($unit) {
          $currency_setting = commerce_currency_load(commerce_default_currency());
          $currency_symbol = $currency_setting['symbol'];

          $unit_names[] = $unit->name;
          $unit_ids[] = $unit->unit_id;

          foreach ($unit_ids as $unit_id) {
            $booking_ids = rooms_booking_ids(array('unit_id' => $unit_id));
          }
        }
      }

      break;

    case 'tours_singleday_availability_reference_default':
      $unit_names = array();
      $unit_ids = array();
      foreach ($items as $delta => $item) {
        if ($field['type'] == 'entityreference') {
          if (empty($item['access'])) {
            continue;
          }
          $unit = ($item['entity']);
        }
        else {
          $unit = rooms_unit_load($item['unit_id']);
        }

        if ($unit) {
          $currency_setting = commerce_currency_load(commerce_default_currency());
          $currency_symbol = $currency_setting['symbol'];

          $unit_names[] = $unit->name;
          $unit_ids[] = $unit->unit_id;

          $form = drupal_get_form('tours_single_day_book_form', $unit);

          $base_price = t('@currency_symbol @amount', array(
            '@currency_symbol' => $currency_symbol,
            '@amount' => number_format($unit->base_price, 2, '.', ''),
          ));

          $element[] = array(
            '#theme' => 'tours_availability_single_day',
            'form' => $form,
            'base_price' => $base_price,
          );
        }
      }

      break;
  }

  if (!empty($booking_ids)) {
    $results = array();

    $bookings = rooms_booking_load_multiple(array_keys($booking_ids), array('type' => 'tour_instance'));

    $currency_setting = commerce_currency_load(commerce_default_currency());
    $currency_symbol = $currency_setting['symbol'];

    foreach ($bookings as $booking) {
      // Ensure start date is good based on the rooms_booking_start_date variable.
      $now = new DateTime();
      $diff1 = $now->setTime(0, 0, 0)->diff($booking->start_date_object);
      $rooms_booking_start_date = variable_get('rooms_booking_start_date', 1);
      // Don't display past/unbookable tours.
      if ($diff1->format("%r%a") >= $rooms_booking_start_date) {
        $results[$booking->start_date_object->format('YmdHis')] = array(
          'id' => $booking->booking_id,
          'start_date' => $booking->start_date_object->format('Y-m-d'),
          'end_date' => $booking->end_date_object->format('Y-m-d'),
          'price' => t('@currency_symbol @amount', array('@currency_symbol' => $currency_symbol, '@amount' => number_format($booking->price / 100, 2, '.', ''))),
          'book_now' => drupal_get_form('tours_book_now_form_' . $booking->booking_id, $booking),
          'settings' => $display['settings'],
        );
      }
    }

    // Order results by start date.
    ksort($results, SORT_NUMERIC);

    if (!empty($results)) {
      $element[] = array(
        '#theme' => 'tours_availability_field_calendar',
        'bookings' => $results,
      );
    }
  }

  return $element;
}

/**
 * Implements hook_field_settings_form().
 */
function tours_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];

  $form = array();
  $form['referenceable_unit_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Unit types that can be referenced'),
    '#multiple' => TRUE,
    '#default_value' => isset($settings['referenceable_unit_types']) ? $settings['referenceable_unit_types'] : array(),
    '#options' => array_map('check_plain', rooms_unit_types_ids()),
  );

  return $form;

}

/**
 * Implements hook_field_validate().
 */
function tours_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Extract unit ids to check.
  $ids = array();

  // Check for non-numeric values.
  // First check non-numeric "nid's to avoid losing time with them.
  foreach ($items as $delta => $item) {
    if (is_array($item) && !empty($item['unit_id'])) {
      if (is_numeric($item['unit_id'])) {
        $ids[] = $item['unit_id'];
      }
      else {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'invalid_unit_id',
          'message' => t('%name: invalid input.',
            array('%name' => $instance['label'])),
        );
      }
    }
  }
}

/**
 * Implements hook_field_widget_info().
 */
function tours_field_widget_info() {
  return array(
    'tours_availability_reference_autocomplete' => array(
      'label'       => t('Autocomplete text field'),
      'description' => t('Display the list of referenceable units as a textfield with autocomplete behaviour.'),
      'field types' => array('tours_availability_reference'),
      'settings'    => array(
        'autocomplete_match' => 'contains',
        'size' => 60,
        'autocomplete_path' => 'tours_availability_reference/autocomplete',
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function tours_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'tours_availability_reference_autocomplete':
      $element += array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['unit_id']) ? $items[$delta]['unit_id'] : NULL,
        '#autocomplete_path' => $instance['widget']['settings']['autocomplete_path'] . '/' . $instance['entity_type'] . '/' . $instance['bundle'] . '/' . $field['field_name'],
        '#size' => $instance['widget']['settings']['size'],
        '#maxlength' => 255,
        '#element_validate' => array('tours_availability_reference_autocomplete_validate'),
        '#value_callback' => 'tours_availability_reference_autocomplete_value',
      );
      break;
  }
  return array('unit_id' => $element);
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function tours_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  if ($instance['display'][$view_mode]['type'] == 'tours_multiday_availability_reference_default') {
    $element['book_now'] = array(
      '#title' => t('Display "Book now"'),
      '#type' => 'checkbox',
      '#default_value' => $settings['book_now'],
    );
  }

  $element['enquire_about'] = array(
    '#title' => t('Display "Enquire about this Tour"'),
    '#type' => 'checkbox',
    '#default_value' => $settings['enquire_about'],
  );

  if ($instance['display'][$view_mode]['type'] == 'tours_singleday_availability_reference_default') {
    $element['display_calendar'] = array(
      '#title' => t('Display as calendar'),
      '#type' => 'checkbox',
      '#default_value' => $settings['display_calendar'],
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function tours_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();
  
  if ($instance['display'][$view_mode]['type'] == 'tours_multiday_availability_reference_default') {
    $summary[] = ($settings['book_now']) ? 'Display "Book now"' : 'Don\'t display "Book now"';
  }
  $summary[] = ($settings['enquire_about']) ? 'Display "Enquire about this Tour"' : 'Don\'t display "Enquire about this Tour"';
  if ($instance['display'][$view_mode]['type'] == 'tours_singleday_availability_reference_default') {
    $summary[] = ($settings['display_calendar']) ? 'Display as calendar' : 'Don\'t display as calendar';
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_widget_error().
 */
function tours_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element['unit_id'], $error['message']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_availability_event_manager_form
 */
function tours_form_rooms_availability_event_manager_form_alter(&$form, $form_state) {
  $unit = rooms_unit_load($form['unit_id']['#value']);
  $tour_types = tours_get_tour_types(TRUE);

  if (in_array($unit->type, $tour_types)) {
    if (isset($form['order'])) {
      unset($form['order']);

      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Create Tour',
        '#submit' => array('tours_add_tour_instance'),
      );

      if ($form_state['submitted']) {
        $commands[] = ctools_modal_command_dismiss();

        print ajax_render($commands);
        exit;
      }
    }
  }
  else {
    // This is not a tours unit, hide the tours booking link.
    if (isset($form['order']['order_link']['tour_instance'])) {
      unset($form['order']['order_link']['tour_instance']);
    }
  }
}

function tours_add_tour_instance($form, &$form_state) {
  global $user;

  // Add the tour instance bookings.
  $unit = rooms_unit_load($form_state['values']['unit_id']);

  if ($unit->type == TOURS_SINGLE_DAY_SLOT || $unit->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
    $start_date = $form_state['values']['rooms_start_date'];
    $end_date = $form_state['values']['rooms_end_date'];
    $end_date = $end_date->modify('+1 day');

    $interval = new DateInterval('P1D');
    $period = new DatePeriod($start_date, $interval, $end_date);

    foreach ($period as $dt) {
      // Ensure we don't have a conflicting booking.
      $rc = new UnitCalendar($unit->unit_id);
      $states = $rc->getStates($dt, $dt);
      // Taking the most conservative approach for now.
      foreach ($states as $state) {
        if ($state != ROOMS_AVAILABLE) {
          drupal_set_message(t('Could not add booking for event with start date of @start and end date of @end, there was an availability conflict!',
                         array('@start' => $instance['value'], '@end' => $instance['value2'])), 'warning');
          continue;
        }
      }

      $profile = tours_get_default_customer_profile();

      $params = array(
        'unit_id' => $unit->unit_id,
        'unit_type' => $unit->type,
        'uid' => $user->uid,
        'customer_id' => $profile->uid,
        'name' => $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'],
        'type' => 'tour_instance',
        'created' => time(),
        'changed' => time(),
        'language' => LANGUAGE_NONE,
        'start_date' => $dt->format('Y-m-d'),
        'end_date' => $dt->format('Y-m-d'),
        'data' => array('group_size' => $unit->max_sleeps),
        'price' => $unit->base_price * 100,
      );
      $booking = rooms_booking_create($params);
      rooms_booking_save($booking);
    }
  }
  else {
    $start_date = $form_state['values']['rooms_start_date'];
    $end_date = $form_state['values']['rooms_end_date'];

    // Ensure we don't have a conflicting booking.
    $rc = new UnitCalendar($unit->unit_id);
    $states = $rc->getStates($start_date, $end_date);
    // Taking the most conservative approach for now.
    foreach ($states as $state) {
      if ($state != ROOMS_AVAILABLE) {
        drupal_set_message(t('Could not add booking for event with start date of @start and end date of @end, there was an availability conflict!',
                       array('@start' => $instance['value'], '@end' => $instance['value2'])), 'warning');
        return;
      }
    }

    $profile = tours_get_default_customer_profile();

    $params = array(
      'unit_id' => $unit->unit_id,
      'unit_type' => $unit->type,
      'uid' => $user->uid,
      'customer_id' => $profile->uid,
      'name' => $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'],
      'type' => 'tour_instance',
      'created' => time(),
      'changed' => time(),
      'language' => LANGUAGE_NONE,
      'start_date' => $start_date->format('Y-m-d'),
      'end_date' => $end_date->format('Y-m-d'),
      'data' => array('group_size' => $unit->max_sleeps),
      'price' => $unit->base_price * 100,
    );
    $booking = rooms_booking_create($params);
    rooms_booking_save($booking);
  }

  $form_state['rebuild'] = TRUE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_type_form
 */
function tours_form_rooms_unit_type_form_alter(&$form, &$form_state, $form_id) {
  $unit_type = $form_state['rooms_unit_type'];
}

function tours_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form_id);
  //dpm($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_edit_form_alter
 */
function tours_form_rooms_unit_edit_form_alter(&$form, &$form_state, $form_id) {
  $tour_types = tours_get_tour_types();

  if ($form['#entity']->type == TOURS_SINGLE_DAY) {
    $form['base_price']['#field_suffix'] = 'per person';

    $form['field_daily_slot']['und']['#title'] = '';
    $form['field_daily_slot']['und']['actions']['ief_add']['#value'] = t('Add time slot');

    $form['field_private_daily_slot']['und']['#title'] = '';
    $form['field_private_daily_slot']['und']['actions']['ief_add']['#value'] = t('Add private time slot');

    $form['availability']['default_state']['#default_value'] = 0;
  }

  if (in_array($form['#entity']->type, $tour_types)) {
    // Change Unit Name to Tour Name.
    $form['name']['#title'] = t('Tour Name');

    // Base price represents the default price for the tour.
    $form['base_price']['#title'] = t('Tour Standard Price');

    // Guest capacity is going to stand in for Tour Capacity
    $form['guest_capacity']['#title'] = t('Tour Capacity');
    $form['guest_capacity']['max_sleeps']['#description'] =
      t('The total number of people that can participate in the tour. The minimum
       number represents the minimum amount required for the tour to take place');

    // Hide chidren and bed arrangement stuff.
    unset($form['data']['bed_arrangement']);
    unset($form['child_capacity']);

    // Hide option to create multiple units.
    $form['multi']['#access'] = FALSE;

    $form['#attached']['css'][] = array(
      'data' => '.rooms-unit-edit-form .form-wrapper.field-name-field-daily-slot .form-wrapper, .rooms-unit-edit-form .form-wrapper.field-name-field-daily-slot, .rooms-unit-edit-form .form-wrapper.field-name-field-private-daily-slot .form-wrapper, .rooms-unit-edit-form .form-wrapper.field-name-field-private-daily-slot { max-width: 100%; display: inline-block; vertical-align: top; } .rooms-unit-edit-form .form-wrapper.field-name-field-private-daily-slot { width: 100%; }',
      'type' => 'inline',
    );
  }
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * Override the availability form to make sense for tours.
 */
function tours_form_update_availability_calendar_form_alter(&$form, &$form_state, $form_id) {
  $unit = rooms_unit_load($form['rooms_update_availability']['unit_id']['#value']);

  if ($unit->type == TOURS_SINGLE_DAY_SLOT || $unit->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
    $form['rooms_update_availability']['#title'] = t('Update Time Slot availability');
    $form['rooms_update_availability']['#collapsed'] = FALSE;

    $form['rooms_update_availability']['actions']['submit']['#value'] = t('Add Instances');
    $form['rooms_update_availability']['actions']['submit']['#submit'][0] = 'tours_add_instances_form_submit';

    $form['rooms_update_availability']['actions']['reset'] = array(
      '#type' => 'submit',
      '#value' => t('Reset time slot availability'),
      '#submit' => array('tours_reset_time_slot_availability'),
      '#limit_validation_errors' => array(),
      '#prefix' => '<div class="button-reset">',
      '#suffix' => '<p>' . t('This will delete all time slot instances that do not have a booking associated with them.') . '</p></div>',
    );

    unset($form['#validate']);
    unset($form['rooms_update_availability']['rooms_date_range']);
    unset($form['rooms_update_availability']['unit_state']);

    $form['#attached']['css'][] = drupal_get_path('module', 'tours') . '/css/tours_manage_availability.css';

    $form['rooms_update_availability']['date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('Starting date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
      '#description' => t('first day tour takes place'),
    );

    $form['rooms_update_availability']['parent1'] = array(
      '#type' => 'fieldset',
      '#title' => t('Repeat Rules'),
      '#collapsible' => TRUE,
      '#tree' => TRUE,
      'parent2' => array(
        '#tree' => TRUE,
        '#required' => TRUE,
        'show_repeat_settings' => array(
          '#type' => 'value',
          '#value' => TRUE,
        ),
        'rrule' => array(
          '#type' => 'date_repeat_rrule',
          '#theme_wrappers' => array('date_repeat_rrule'),
          '#default_value' => isset($instance->repeat_rule) ? $instance->repeat_rule : '',
          '#date_timezone' => date_default_timezone(),
          '#date_label_position' => 'above',
          '#date_format' => 'Y-m-d',
          '#date_increment' => 1,
          '#date_year_range' => '-0:+1',
          '#date_repeat_widget' => 'date_popup',
          '#date_flexible' => 0,
          '#date_repeat_collapsed' => TRUE,
        ),
      ),
    );
  }
  elseif ($unit->type == TOURS_MULTI_DAY) {
    $form['rooms_update_availability']['actions']['submit']['#value'] = t('Add Instances');
    $form['rooms_update_availability']['actions']['submit']['#submit'][0] = 'tours_add_instances_form_submit';
    $form['rooms_update_availability']['#description'] = t('Enter tour dates/times.');

    unset($form['#validate']);
    unset($form['rooms_update_availability']['rooms_date_range']);
    unset($form['rooms_update_availability']['unit_state']);

    $form['#attached']['css'][] = drupal_get_path('module', 'tours') . '/css/tours_manage_availability.css';

    $form['rooms_update_availability']['date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('Starting date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );

    $form['rooms_update_availability']['end_date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('End date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );

    $form['rooms_update_availability']['parent1'] = array(
      '#type' => 'fieldset',
      '#title' => t('Repeat Tour Rules'),
      '#collapsible' => TRUE,
      '#tree' => TRUE,
      'parent2' => array(
        '#tree' => TRUE,
        '#required' => TRUE,
        'show_repeat_settings' => array(
          '#type' => 'value',
          '#value' => TRUE,
        ),
        'rrule' => array(
          '#type' => 'date_repeat_rrule',
          '#theme_wrappers' => array('date_repeat_rrule'),
          '#default_value' => isset($instance->repeat_rule) ? $instance->repeat_rule : '',
          '#date_timezone' => date_default_timezone(),
          '#date_label_position' => 'above',
          '#date_format' => 'Y-m-d',
          '#date_increment' => 1,
          '#date_year_range' => '-0:+1',
          '#date_repeat_widget' => 'date_popup',
          '#date_flexible' => 0,
          '#date_repeat_collapsed' => TRUE,
        ),
      ),
    );
  }
}

/**
 * Submit function for 'Reset time slot availability'.
 */
function tours_reset_time_slot_availability($form, &$form_state) {
  // Delete every booking for that single day tour slot unit
  // that does not have an order associated with it.
  $single_day_tour_slot = $form['rooms_update_availability']['unit_id']['#value'];

  $results = db_select('rooms_bookings', 'b')
                ->fields('b', array('booking_id'))
                ->condition('unit_id', $single_day_tour_slot)
                ->execute()
                ->fetchAllKeyed(0, 0);

  foreach (array_keys($results) as $booking_id) {
    $booking = rooms_booking_load($booking_id);

    if (empty($booking->field_tour_orders)) {
      rooms_booking_delete($booking);
    }
  }
}

/**
 * Validation for tour instance repeating date add form.
 */
function tours_add_instances_form_submit($form, &$form_state) {
  global $user;

  // Set up variables.
  $rrule = $form_state['values']['parent1']['parent2']['rrule'];
  $rrule_values = date_ical_parse_rrule(NULL, $rrule);
  $timezone = date_default_timezone();

  $start_date = $form_state['values']['date'];
  $end_date = (isset($form_state['values']['end_date'])) ? $form_state['values']['end_date'] : $form_state['values']['date'];

  // Calculate the event duration.
  $start = new DateObject($start_date, $timezone, 'Y-m-d');
  $end = new DateObject($end_date, $timezone, 'Y-m-d');
  $duration = $start->difference($end);

  // Figure out when to stop.
  $start_datetime = date_format($start, DATE_FORMAT_DATETIME);
  if (!empty($rrule_values['UNTIL']['datetime'])) {
    $end = date_ical_date($rrule_values['UNTIL'], $timezone);
    $end_datetime = date_format($end, DATE_FORMAT_DATETIME);
  }
  else {
    $end_datetime = NULL;
  }

  // Split the RRULE into RRULE, EXDATE, and RDATE parts.
  $parts = date_repeat_split_rrule($rrule);
  $parsed_exceptions = (array) $parts[1];
  $exceptions = array();
  foreach ($parsed_exceptions as $exception) {
    $date = date_ical_date($exception, $timezone);
    $exceptions[] = date_format($date, 'Y-m-d');
  }

  $parsed_rdates = (array) $parts[2];
  $additions = array();
  foreach ($parsed_rdates as $rdate) {
    $date = date_ical_date($rdate, $timezone);
    $additions[] = date_format($date, 'Y-m-d');
  }

  // Calculate the dates for bookings we want to add.
  $dates = date_repeat_calc($rrule, $start_datetime, $end_datetime, $exceptions, $timezone, $additions);
  $value = array();
  foreach ($dates as $delta => $date) {
    // date_repeat_calc always returns DATE_DATETIME dates, which is
    // not necessarily $field['type'] dates.
    // Convert returned dates back to db timezone before storing.
    $date_start = new DateObject($date, $timezone, DATE_FORMAT_DATETIME);
    $date_end = clone($date_start);
    date_modify($date_end, '+' . $duration . ' seconds');
    $value[$delta] = array(
      'value' => date_format($date_start, 'Y-m-d'),
      'value2' => date_format($date_end, 'Y-m-d'),
      'date_start' => $date_start,
      'date_end' => $date_end,
      'offset' => date_offset_get($date_start),
      'offset2' => date_offset_get($date_end),
      'timezone' => $timezone,
      'rrule' => $rrule,
    );
  }

  // Add the tour instance bookings.
  $unit = rooms_unit_load($form_state['values']['unit_id']);
  foreach ($value as $instance) {
    // Ensure we don't have a conflicting booking.
    $rc = new UnitCalendar($unit->unit_id);
    $states = $rc->getStates($instance['date_start'], $instance['date_end']);
    // Taking the most conservative approach for now.
    foreach ($states as $state) {
      if ($state != ROOMS_AVAILABLE) {
        drupal_set_message(t('Could not add booking for event with start date of @start and end date of @end, there was an availability conflict!',
                       array('@start' => $instance['value'], '@end' => $instance['value2'])), 'warning');
        continue 2;
      }
    }

    $profile = tours_get_default_customer_profile();

    $params = array(
      'unit_id' => $unit->unit_id,
      'unit_type' => $unit->type,
      'uid' => $user->uid,
      'customer_id' => $profile->uid,
      'name' => $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'],
      'type' => 'tour_instance',
      'created' => time(),
      'changed' => time(),
      'language' => LANGUAGE_NONE,
      'start_date' => $instance['value'],
      'end_date' => $instance['value2'],
      'data' => array('group_size' => $unit->max_sleeps),
      'price' => $unit->base_price * 100,
    );
    $booking = rooms_booking_create($params);
    rooms_booking_save($booking);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modifications to tour booking form.
 */
function tours_form_rooms_booking_edit_form_alter(&$form, &$form_state) {
  if ($form['#bundle'] == 'tour_instance') {
    // Allow single day bookings.
    $form_state['single_day_bookings'] = TRUE;

    // Hide 'children' selection.
    $form['data']['group_size_children']['#access'] = FALSE;
    $form['data']['group_size_children']['#access'] = FALSE;

    $profile = tours_get_default_customer_profile();
    $form['client']['#default_value'] = $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] . ':' . $profile->profile_id;

    if (($key = array_search('rooms_booking_manager_rooms_booking_edit_form_submit', $form['actions']['submit']['#submit'])) !== FALSE) {
      unset($form['actions']['submit']['#submit'][$key]);
    }
  }
}

/**
 * Implements hook_menu_alter().
 */
function tours_menu_alter(&$items) {
  $items['admin/rooms/units/unit/%rooms_unit/availability']['page callback'] = 'tours_availability_page';
}

/**
 * Implements hook_entity_info_alter().
 */
function tours_entity_info_alter(&$entity_info) {
  $entity_info['rooms_unit']['inline entity form'] = array(
    'controller' => 'RoomsUnitInlineEntityFormController',
  );
}

/**
 * Implements hook_entity_insert
 */
function tours_entity_insert($entity, $type) {
}

/**
 * Implements hook_entity_update
 */
function tours_entity_update($entity, $type) {
}

/**
 * Implements hook_views_default_views_alter().
 */
function tours_views_default_views_alter(&$views) {
  if (isset($views['bookings'])) {
    $views['bookings']->disabled = TRUE;
  }

  if (isset($views['bookable_units'])) {
    $handler =& $views['bookable_units']->display['default']->handler;

    $handler->display->display_options['filters']['type']['value'] = array(
      'multi_day_tour' => 'multi_day_tour',
      'single_day_tour' => 'single_day_tour',
    );
  }
}


/**
 * Commerce hooks.
 */

/**
 * Implements hook_commerce_line_item_type_info().
 */
function tours_commerce_line_item_type_info() {
  return array(
    'tours_booking' => array(
      'name' => t('Tours Booking'),
      'description' => t('Represents a booking of a Rooms Tour product.'),
      'product' => TRUE,
      'add_form_submit_value' => t('Add product'),
      'base' => 'tours_line_item',
    ),
  );
}

/**
 * Ensures the booking line item type contains a product reference field and
 * all other rooms fields required for a booking.
 *
 * @param array $line_item_type
 *   The line item type object.
 */
function tours_line_item_configuration($line_item_type) {
  $type = $line_item_type['type'];

  // Get the info about the fields and instances we need to create.
  module_load_include('inc', 'tours', 'includes/tours.fields');
  $field_data = _tours_line_item_type_fields();

  // Create the product reference field for the line item type.
  commerce_product_line_item_configuration($line_item_type);

  // For each field, check whether it already exists create it if it doesn't
  foreach ($field_data['fields'] as $field_name => $field_info) {
    $field = field_info_field($field_name);
    $instance = field_info_instance('commerce_line_item', $field_name, $type);

    if (empty($field)) {
      field_create_field($field_data['fields'][$field_name]);
    }
    if (empty($instance)) {
      field_create_instance($field_data['instances'][$field_name]);
    }
  }
}

/**
 * Implements hook_line_item_title().
 */
function tours_line_item_title($line_item) {
  // Use the line item's label for the title.
  return ($line_item->line_item_label);
}

/**
 * Implements hook_default_rules_configuration_alter().
 */
function tours_default_rules_configuration_alter(&$configs) {
  if (isset($configs['rooms'])) {
    $configs['rooms']->action('tours_price_apply', array('#_needs_processing' => TRUE, 'commerce_line_item:select' => 'commerce-line-item'));
  }
}

/**
 * Implements hook_commerce_checkout_complete().
 */
function tours_commerce_checkout_complete($order) {
  foreach ($order->commerce_line_items as $lang => $item) {
    foreach ($item as $item_id) {
      $line_item = commerce_line_item_load($item_id['line_item_id']);
      if ($line_item->type == 'tours_booking') {
        $booking = rooms_booking_load($line_item->tours_booking_reference[LANGUAGE_NONE][0]['target_id']);

        $already_added = FALSE;
        if (isset($booking->field_tour_orders[LANGUAGE_NONE])) {
          foreach ($booking->field_tour_orders[LANGUAGE_NONE] as $order_id) {
            if ($order_id['target_id'] == $order->order_id) {
              $already_added = TRUE;
            }
          }
        }

        if (!$already_added) {
          $booking->field_tour_orders[LANGUAGE_NONE][]['target_id'] = $order->order_id;

          if (tours_booking_free_quantity($booking) <= 0) {
            $booking->booking_status = 1;
          }

          rooms_booking_save($booking);
        }

        // Set booking to confirmed if minimum occupancy has been reached.
        /*if (isset($line_item->tours_booked_unit_id)) {
          $unit = rooms_unit_load($line_item->tours_booked_unit_id[LANGUAGE_NONE][0]['value']);
          if (tours_booking_quantity_booked($booking) >= $unit->min_sleeps) {
            $booking->booking_status = 1;
            rooms_booking_save($booking);
          }
        }*/
      }
    }
  }
}


/**
 * Rooms hooks.
 */

/**
 * Implements hook_rooms_availability_update().
 */
function tours_rooms_availability_update($response, $events) {
  foreach ($response as $event_id => $code) {
    if ($code == ROOMS_UPDATED) {
      foreach ($events as $event) {
        if ($event->id == $event_id) {
          $unit = rooms_unit_load($event->unit_id);
          if ($unit->type == TOURS_SINGLE_DAY_SLOT || $unit->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
            $unit_id = $unit->field_day_tour[LANGUAGE_NONE][0]['target_id'];

            $start_date = $event->start_date;
            $end_date = $event->end_date;

            if ($event_id < 0) {
              $event = new BookingEvent($unit_id, ROOMS_PART_BOOKED, $start_date, $end_date);
              $uc = new UnitCalendar($unit_id);
              $responses = $uc->updateCalendar(array($event));
            }
            else {
              $event = new BookingEvent($unit_id, ROOMS_AVAILABLE, $start_date, $end_date);
              $uc = new UnitCalendar($unit_id);
              $responses = $uc->updateCalendar(array($event));
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_rooms_price_modifier_alter().
 */
function tours_rooms_price_modifier_alter(&$price_modifiers, $booking_info) {
  $tour_types = tours_get_tour_types();

  // If this is a tour, modify the pricing to be per user, for the entire
  // booking period.
  if (in_array($booking_info['unit']->type, $tour_types)) {
    $length = $booking_info['end_date']->diff($booking_info['start_date']);
    $days = $length->days;
    if ($days > 1) {
      // If the tour is more than 1 day long, adjust the
      // total price to the base price.
      $price_modifiers['total'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_SUB,
        '#amount' => $booking_info['unit']->base_price,
        '#quantity' => ($days - 1),
      );
    }

    // Figure out the group size.
    if (isset($booking_info['booking_parameters']['group_size'])) {
      $group_size = $booking_info['booking_parameters']['group_size'];
    }
    elseif (isset($booking_info['booking_parameters'][0]['adults'])) {
      $group_size = $booking_info['booking_parameters'][0]['adults'];
    }
    else {
      $group_size = $booking_info['booking_parameters']['adults'];
    }

    // Add the base price for each additional person.
    if ($group_size > 1) {
      $amount_per_additional_person = $booking_info['unit']->base_price;
      $price_modifiers['additional'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_ADD,
        '#amount' => $amount_per_additional_person,
        '#quantity' => ($group_size - 1),
      );
    }
  }
}


/**
 * Custom functions.
 */


/**
 * Set a default customer if not already present.
 */
function tours_get_default_customer_profile() {
  // Look for a customer profile for the site admin.
  $profile_id = db_select('commerce_customer_profile', 'cc')
    ->fields('cc', array('profile_id'))
    ->condition('uid', 1)
    ->range(0,1)
    ->execute()
    ->fetchField();
  if ($profile_id) {
    $profile = commerce_customer_profile_load($profile_id);
  }
  else {
    // If there's not one already existing, create it.
    $profile = commerce_customer_profile_new($type = 'billing', $uid = 1);
    $profile->status = '1';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['country'] = 'US';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['administrative_area'] = 'NM';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['postal_code'] = '87501';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['locality'] = 'Santa Fe';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['thoroughfare'] = '804 Don Gaspar';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] = 'Tours Owner';
    commerce_customer_profile_save($profile);
  }
  return($profile);
}

/**
 *
 */
function tours_set_tour_dates($entity) {
  $start_date = null;
  $end_date = null;

  // Check whether start and end dates are set.
  if (isset($entity->field_tour_dates[LANGUAGE_NONE][0]['value'])) {
    $start_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value']);
    $end_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value2']);
  }

  if (!isset($start_date)) {
    drupal_set_message(t('Tour dates have not been set'));
    return FALSE;
  } else {
    $tour_event = new BookingEvent($entity->unit_id, ROOMS_AVAILABLE, $start_date, $end_date);

    $events = array($tour_event);
    $ac = new UnitCalendar($entity->unit_id);
    $ac->updateCalendar($events);
  }

  return TRUE;
}

/**
 * Tour availability callback page
 *
 * @param \RoomsUnit $rooms_unit
 * @param string $year
 * @param string $month
 * @return array
 */
function tours_availability_page(RoomsUnit $rooms_unit, $year = '', $month = '') {
  if (in_array($rooms_unit->type, tours_get_tour_types(TRUE))) {
    // Set the page title.
    drupal_set_title(t('Edit @unit_name Tour Dates', array('@unit_name' => $rooms_unit->name)));

    // Add styles.
    rooms_availability_modal_style();

    // Get the current page's URL, striped of the year and month args.
    // This allows us to place this page anywhere, including at
    // unit/%/availability  or  admin/rooms/units/unit/%/availability
    list($url) = explode('/' . $year . '/' . $month, current_path());

    $js_file = drupal_get_path('module', 'rooms_availability') . '/js/rooms_availability.js';
    $css_file = drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css';
    // Show full day events on calendar.
    if (variable_get('rooms_calendar_events_view', '0') == '1') {
      $js_file = drupal_get_path('module', 'rooms_availability') . '/js/rooms_availability_full_day.js';
    }
    return array(
      '#theme' => 'rooms_three_month_calendar',
      '#url' => $url,
      '#form' => drupal_get_form('update_availability_calendar_form', $rooms_unit->unit_id, $year, $month),
      '#year' => $year,
      '#month' => $month,
      '#attached' => array(
        'css' => array(
          $css_file,
        ),
        'js' => array(
          $js_file,
          array(
            'data' => array('roomsAvailability' => array('roomID' => $rooms_unit->unit_id)),
            'type' => 'setting',
          ),
        ),
      ),
    );

  }
  else {
    return rooms_availability_page($rooms_unit, $year, $month);
  }
}

/**
 * Return all tour types.
 * @param boolean $all
 */
function tours_get_tour_types($all = FALSE) {
  // Typically we are interested in the multi_day + single day tours, not the single day slots
  if ($all) {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY, TOURS_SINGLE_DAY_SLOT, TOURS_PRIVATE_SINGLE_DAY_SLOT);
  } else {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY);
  }
}

/**
 * Menu callback for the autocomplete results.
 */
function tours_availability_reference_autocomplete($entity_type, $bundle, $field_name, $string = '') {
  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  $options = array(
    'string' => $string,
    'match' => $instance['widget']['settings']['autocomplete_match'],
    'limit' => 10,
  );
  $references = tours_availability_reference_potential_references($field, $options);

  $matches = array();
  foreach ($references as $id => $row) {
    // Markup is fine in autocompletion results (might happen when rendered
    // through Views) but we want to remove hyperlinks.
    $suggestion = preg_replace('/<a href="([^<]*)">([^<]*)<\/a>/', '$2', $row['rendered']);
    // Add a class wrapper for a few required CSS overrides.
    $matches[$row['title'] . " [unit_id:$id]"] = '<div class="reference-autocomplete">' . $suggestion . '</div>';
  }

  drupal_json_output($matches);
}

/**
 * Retrieves an array of candidate referenceable booking units.
 *
 * This info is used in various places (allowed values, autocomplete
 * results, input validation...). Some of them only need the nids,
 * others nid + titles, others yet nid + titles + rendered row (for
 * display in widgets).
 *
 * The array we return contains all the potentially needed information,
 * and lets consumers use the parts they actually need.
 *
 * @param array $field
 *   The field definition.
 * @param array $options
 *   An array of options to limit the scope of the returned list. The following
 *   key/value pairs are accepted:
 *   - string: string to filter unit names on (used by autocomplete).
 *   - match: operator to match the above string against, can be any of:
 *     'contains', 'equals', 'starts_with'. Defaults to 'contains'.
 *   - ids: array of specific unit ids to lookup.
 *   - limit: maximum size of the the result set. Defaults to 0 (no limit).
 *
 * @return array
 *   An array of valid units in the form:
 *   array(
 *     unit_id => array(
 *       'name' => The unit title,
 *       'rendered' => The text to display in widgets (can be HTML)
 *     ),
 *     ...
 *   )
 */
function tours_availability_reference_potential_references($field, $options = array()) {
  // Fill in default options.
  $options += array(
    'string' => '',
    'match' => 'contains',
    'ids' => array(),
    'limit' => 0,
  );

  $results = &drupal_static(__FUNCTION__, array());

  // Create unique id for static cache.
  $cid = $field['field_name'] . ':' . $options['match'] . ':'
    . ($options['string'] !== '' ? $options['string'] : implode('-', $options['ids']))
    . ':' . $options['limit'];
  if (!isset($results[$cid])) {
    $references = FALSE;

    if ($references === FALSE) {
      $references = _tours_availability_reference_potential_references($field, $options);
    }

    // Store the results.
    $results[$cid] = !empty($references) ? $references : array();
  }

  return $results[$cid];
}

/**
 * Helper function for node_reference_potential_references().
 *
 * List of referenceable nodes defined by content types.
 */
function _tours_availability_reference_potential_references($field, $options) {
  // Avoid useless work.
  if (!isset($field['settings']['referenceable_unit_types'])) {
    return array();
  }

  if (!count($field['settings']['referenceable_unit_types'])) {
    return array();
  }

  $query = db_select('rooms_units', 'u');
  $unit_unit_id_alias = $query->addField('u', 'unit_id');
  $unit_name_alias = $query->addField('u', 'name', 'name');
  $unit_type_alias = $query->addField('u', 'type', 'type');

  if (is_array($field['settings']['referenceable_unit_types'])) {
    $query->condition('u.type', $field['settings']['referenceable_unit_types'], 'IN');
  }

  if ($options['string'] !== '') {
    switch ($options['match']) {
      case 'contains':
        $query->condition('u.name', '%' . $options['string'] . '%', 'LIKE');
        break;

      case 'starts_with':
        $query->condition('u.name', $options['string'] . '%', 'LIKE');
        break;

      case 'equals':
      default:
        // No match type or incorrect match type: use "=".
        $query->condition('u.name', $options['string']);
        break;
    }
  }

  if ($options['ids']) {
    $query->condition('u.unit_id', $options['ids'], 'IN');
  }

  if ($options['limit']) {
    $query->range(0, $options['limit']);
  }

  $query
    ->orderBy($unit_name_alias)
    ->orderBy($unit_type_alias);

  $result = $query->execute()->fetchAll();
  $references = array();
  foreach ($result as $unit) {
    $references[$unit->unit_id] = array(
      'title'    => $unit->name,
      'rendered' => check_plain($unit->name),
    );
  }
  return $references;
}

/**
 * Helper function - return number of slots booked for a tour
 * instance.
 */
function tours_booking_quantity_booked($booking) {
  $unit = rooms_unit_load($booking->unit_id);

  $quantity_booked = 0;

  if (isset($booking->field_tour_orders[LANGUAGE_NONE])) {
    foreach ($booking->field_tour_orders[LANGUAGE_NONE] as $order_id) {
      $order = commerce_order_load($order_id['target_id']);

      if ($order !== FALSE) {
        foreach ($order->commerce_line_items as $lang => $item) {
          foreach ($item as $item_id) {
            $line_item = commerce_line_item_load($item_id['line_item_id']);
            $quantity_booked += $line_item->tours_booking_number_people[LANGUAGE_NONE][0]['value'];
          }
        }
      }
    }
  }

  return $quantity_booked;
}

/**
 * Helper function - return number of booking slots available for a tour
 * instance.
 */
function tours_booking_free_quantity($booking) {
  $unit = rooms_unit_load($booking->unit_id);

  $free_quantity = $unit->max_sleeps;

  if (isset($booking->field_tour_orders[LANGUAGE_NONE])) {
    foreach ($booking->field_tour_orders[LANGUAGE_NONE] as $order_id) {
      $order = commerce_order_load($order_id['target_id']);

      if ($order !== FALSE) {
        foreach ($order->commerce_line_items as $lang => $item) {
          foreach ($item as $item_id) {
            $line_item = commerce_line_item_load($item_id['line_item_id']);

            $free_quantity -= $line_item->tours_booking_number_people[LANGUAGE_NONE][0]['value'];
          }
        }
      }
    }
  }

  return $free_quantity;
}

/**
 * Implements hook_forms().
 *
 * Allows the book now form to be repeated multiple times on a page.
 * See https://api.drupal.org/comment/48318
 */
function tours_forms($form_id, $args) {
  $forms = array();
  if (strncmp($form_id, 'tours_book_now_form_', 20) === 0) {
    $forms[$form_id] = array('callback' => 'tours_book_now_form');
  }

  return $forms;
}

function tours_single_day_book_form($form, &$form_state, $tour) {
  if (isset($form_state['triggering_element'])) {
    if ($form_state['triggering_element']['#name'] == 'date') {
      $form_state['values']['time'] = '_none';
      $form_state['input']['time'] = '_none';

      $form_state['values']['participants'] = '_none';
      $form_state['input']['participants'] = '_none';
    }
    elseif ($form_state['triggering_element']['#name'] == 'time') {
      $form_state['values']['participants'] = '_none';
      $form_state['input']['participants'] = '_none';
    }
  }

  $form['tour'] = array(
    '#type' => 'hidden',
    '#value' => $tour->unit_id,
  );

  $form['date'] = array(
    '#title' => t('Select a date'),
    '#type' => 'date_popup',
    '#flavour' => 'inline',
    '#date_format' => 'Y-m-d',
    '#datepicker_options' => array('minDate' => '+1d', 'maxDate' => '+1y'),
    '#restrictions' => array(
      'allowed_values' => array(
        'type' => 'tours',
        'tour_id' => $tour->unit_id,
      ),
    ),
    '#ajax' => array(
      'wrapper' => 'single-day-tour-container',
      'callback' => 'tours_single_day_ajax_callback',
    ),
  );

  $form['container'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="single-day-tour-container">',
    '#suffix' => '</div>',
  );

  $time_options = array('_none' => t('select time'));
  $form['container']['time'] = array(
    '#type' => 'select',
    '#options' => $time_options,
    '#disabled' => TRUE,
    '#default_value' => isset($form_state['values']['time']) ? $form_state['values']['time'] : '_none',
    '#ajax' => array(
      'wrapper' => 'single-day-tour-container',
      'callback' => 'tours_single_day_ajax_callback',
    ),
  );

  if (isset($form_state['values']['date']) &&
      $form_state['values']['date'] != '' && $form_state['values']['date'] != '_none') {
    $form['container']['time']['#disabled'] = FALSE;

    // Single-Day Tour Slot
    $single_day_tour_slots = array();
    foreach ($tour->field_daily_slot[LANGUAGE_NONE] as $slot) {
      $single_day_tour_slots[] = $slot['target_id'];
    }

    $results = db_select('rooms_bookings', 'b')
                ->fields('b', array('unit_id'))
                ->condition('booking_status', '0')
                ->condition('unit_id', $single_day_tour_slots)
                ->condition('start_date', $form_state['values']['date'])
                ->execute()
                ->fetchAll();

    $available_slots = array();
    foreach ($results as $result) {
      $available_slots[] = $result->unit_id;
    }

    foreach ($tour->field_daily_slot[LANGUAGE_NONE] as $id => $slot) {
      $daily_slot = rooms_unit_load($slot['target_id']);

      if (in_array($daily_slot->unit_id, $available_slots)) {
        $time_options[$daily_slot->unit_id] = $daily_slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value_formatted'] . ' - ' . $daily_slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value2_formatted'];
      }
    }

    // Private Single-Day Tour Slot
    $single_day_private_tour_slots = array();
    foreach ($tour->field_private_daily_slot[LANGUAGE_NONE] as $slot) {
      $single_day_private_tour_slots[] = $slot['target_id'];
    }

    $results = db_select('rooms_bookings', 'b')
                ->fields('b', array('unit_id'))
                ->condition('booking_status', '0')
                ->condition('unit_id', $single_day_private_tour_slots)
                ->condition('start_date', $form_state['values']['date'])
                ->execute()
                ->fetchAll();

    $available_slots = array();
    foreach ($results as $result) {
      $available_slots[] = $result->unit_id;
    }

    foreach ($tour->field_private_daily_slot[LANGUAGE_NONE] as $id => $slot) {
      $daily_slot = rooms_unit_load($slot['target_id']);

      if (in_array($daily_slot->unit_id, $available_slots)) {
        $time_options[$daily_slot->unit_id] = $daily_slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value_formatted'] . ' - ' . $daily_slot->field_day_tour_time_slot[LANGUAGE_NONE][0]['value2_formatted'] . ' - Private Tour';
      }
    }

    $form['container']['time']['#options'] = $time_options;
  }

  $participants_options = array('_none' => t('number of participants'));
  $form['container']['participants'] = array(
    '#type' => 'select',
    '#options' => $participants_options,
    '#disabled' => TRUE,
    '#default_value' => isset($form_state['values']['participants']) ? $form_state['values']['participants'] : '_none',
    '#ajax' => array(
      'wrapper' => 'single-day-tour-container',
      'callback' => 'tours_single_day_ajax_callback',
    ),
  );

  if (isset($form_state['values']['time']) &&
      $form_state['values']['time'] != '' && $form_state['values']['time'] != '_none') {
    $form['container']['participants']['#disabled'] = FALSE;

    $booking_id = db_select('rooms_bookings', 'b')
                  ->fields('b', array('booking_id'))
                  ->condition('booking_status', '0')
                  ->condition('unit_id', $form_state['values']['time'])
                  ->condition('start_date', $form_state['values']['date'])
                  ->execute()
                  ->fetchField();

    $booking = rooms_booking_load($booking_id);

    $participants = tours_booking_free_quantity($booking);

    $participants_options = array_merge($participants_options, range(1, $participants));

    $form['container']['participants']['#options'] = $participants_options;
  }

  $form['container']['price'] = array(
    '#type' => 'markup',
    '#markup' => '<div></div>',
  );

  $form['container']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Book Now'),
    '#disabled' => TRUE,
  );

  if (isset($form_state['values']['participants']) &&
      $form_state['values']['participants'] != '' && $form_state['values']['participants'] != '_none') {
    $form['container']['submit']['#disabled'] = FALSE;

    $currency_setting = commerce_currency_load(commerce_default_currency());
    $currency_symbol = $currency_setting['symbol'];

    $daily_slot = rooms_unit_load($form_state['values']['time']);

    if ($daily_slot->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
      $temp_price = '';
      $max_price = '';
      $max_people = 0;
      $diff = PHP_INT_MAX;

      $participants = $form_state['values']['participants'] + 1;

      if (isset($daily_slot->field_variable_pricing['und'])) {
        foreach ($daily_slot->field_variable_pricing['und'] as $pricing) {
          if ($participants <= $pricing['first']) {
            if (($pricing['first'] - $participants) < $diff) {
              $diff = $pricing['first'] - $participants;
              $temp_price = $pricing['second'];
            }
          }

          if ($max_people < $pricing['first']) {
            $max_people = $pricing['first'];
            $max_price = $pricing['second'];
          }
        }
      }

      if ($temp_price) {
        $price = t('@currency_symbol @amount', array(
          '@currency_symbol' => $currency_symbol,
          '@amount' => number_format($temp_price, 2, '.', ''),
        ));
      }
      elseif ($max_price) {
        $price = t('@currency_symbol @amount', array(
          '@currency_symbol' => $currency_symbol,
          '@amount' => number_format($max_price, 2, '.', ''),
        ));
      }
      else {
        $price = t('@currency_symbol @amount', array(
          '@currency_symbol' => $currency_symbol,
          '@amount' => number_format($daily_slot->base_price * ($form_state['values']['participants'] + 1), 2, '.', ''),
        ));
      }
    }
    else {
      $price = t('@currency_symbol @amount', array(
        '@currency_symbol' => $currency_symbol,
        '@amount' => number_format($daily_slot->base_price * ($form_state['values']['participants'] + 1), 2, '.', ''),
      ));
    }

    $form['container']['price']['#markup'] = '<div class="form-item form-group">' . t('Price') . ': ' . $price . '</div>';
  }

  return $form;
}

function tours_single_day_ajax_callback($form, &$form_state) {
  return $form['container'];
}

function tours_single_day_book_form_submit($form, &$form_state) {
  global $user;
  module_load_include('inc', 'tours', 'tours.commerce');

  $order = commerce_cart_order_load($user->uid);
  if (empty($order)) {
    $order = commerce_order_new($user->uid, 'pending');
  }

  $values = $form_state['values'];

  $tour = rooms_unit_load($values['tour']);
  $date = $values['date'];
  $daily_slot = rooms_unit_load($values['time']);
  $participants = $values['participants'] + 1;

  $booking_id = db_select('rooms_bookings', 'b')
                  ->fields('b', array('booking_id'))
                  ->condition('booking_status', '0')
                  ->condition('unit_id', $values['time'])
                  ->condition('start_date', $values['date'])
                  ->execute()
                  ->fetchField();

  $booking_parameters = array('adults' => $participants, 'children' => 0);
  $agent = new AvailabilityAgent(new DateTime($date), new DateTime($date), $booking_parameters);
  $price_modifiers = array();

  $unit = array(
    'unit' => $daily_slot,
    'state' => ROOMS_AVAILABLE,
  );

  $line_item = tours_create_line_item($unit, $agent, $booking_parameters, $price_modifiers);

  $line_item->tours_booking_reference[LANGUAGE_NONE][0]['target_id'] = $booking_id;

  // Add line item to cart.
  $line_item = commerce_cart_product_add($user->uid, $line_item, FALSE);

  // Refresh line items price and redirect to bookings page.
  commerce_cart_order_refresh(commerce_cart_order_load($user->uid));

  $form_state['redirect'] = 'bookings';
}

function tours_book_now_form($form, &$form_state, $booking) {
  $free_quantity = tours_booking_free_quantity($booking);

  if ($free_quantity > 0) {
    $form['booking_id'] = array(
      '#type' => 'hidden',
      '#value' => $booking->booking_id,
    );

    $form['group_size'] = array(
      '#title' => t('Quantity'),
      '#type' => 'select',
      '#options' => range(1, $free_quantity),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Book Now'),
    );
  }

  return $form;
}

function tours_book_now_form_submit($form, &$form_state) {
  global $user;
  module_load_include('inc', 'tours', 'tours.commerce');

  $order = commerce_cart_order_load($user->uid);
  if (empty($order)) {
    $order = commerce_order_new($user->uid, 'pending');
  }

  $booking_id = $form_state['values']['booking_id'];
  $group_size = $form_state['values']['group_size'] + 1;

  $booking = rooms_booking_load($booking_id);

  $unit = array(
    'unit' => rooms_unit_load($booking->unit_id),
    'state' => ROOMS_AVAILABLE,
  );

  $sd = $booking->start_date_object;
  $ed = $booking->end_date_object;

  $booking_parameters = array('adults' => 1, 'children' => 0);

  $agent = new AvailabilityAgent($sd, $ed, $booking_parameters);

  $price_modifiers = array();

  for ($i = 0; $i < $group_size; $i++) {
    $line_item = tours_create_line_item($unit, $agent, $booking_parameters, $price_modifiers);

    $line_item->tours_booking_reference[LANGUAGE_NONE][0]['target_id'] = $booking->booking_id;

    // Add line item to cart.
    $line_item = commerce_cart_product_add($user->uid, $line_item, FALSE);
  }

  // Refresh line items price and redirect to bookings page.
  commerce_cart_order_refresh(commerce_cart_order_load($user->uid));

  $form_state['redirect'] = 'bookings';
}

/**
 * Calculates the price for rooms_booking line item types.
 *
 * @param object $line_item
 *   Line item to modify.
 */
function tours_price_apply($line_item) {
  if ($line_item->type == 'tours_booking') {
    if ($item = field_get_items('commerce_line_item', $line_item, 'commerce_product')) {
      $product = commerce_product_load($item[0]['product_id']);
      if ($product->sku != 'ROOMS-BASIC-BOOKING') {
        return;
      }
    }
    $amount = $line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'];

    $start_date = new DateTime($line_item->tours_booking_dates[LANGUAGE_NONE][0]['value']);
    $end_date = new DateTime($line_item->tours_booking_dates[LANGUAGE_NONE][0]['value2']);

    $unit_id = $line_item->tours_booked_unit_id[LANGUAGE_NONE][0]['value'];
    $unit = rooms_unit_load($unit_id);

    // First set up price modifiers.
    $price_options = is_array(field_get_items('commerce_line_item', $line_item, 'rooms_booking_options')) ? field_get_items('commerce_line_item', $line_item, 'rooms_booking_options') : array();

    // Convert Price options in Price modifiers.
    foreach ($price_options as $option) {
      $price_modifiers[strtolower(str_replace(array(':', ' '), '_', $option['name']))] = array(
        '#name' => $option['name'],
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => $option['operation'],
        '#amount' => $option['value'],
        '#quantity' => $option['quantity'],
      );
    }

    $adults = $line_item->tours_booking_number_people[LANGUAGE_NONE][0]['value'];
    $children = $line_item->tours_booking_number_people[LANGUAGE_NONE][1]['value'];
    $childrens_age = (isset($line_item->tours_booking_children_ages[LANGUAGE_NONE])) ?
                      $line_item->tours_booking_children_ages[LANGUAGE_NONE] : array();

    $booking_info = array(
      'start_date' => clone($start_date),
      'end_date' => clone($end_date),
      'unit' => $unit,
      'booking_parameters' => array(
        'group_size' => $adults,
        'group_size_children' => $children,
        'childrens_age' => $childrens_age,
      ),
    );

    // Give other modules a chance to change the price modifiers.
    drupal_alter('rooms_price_modifier', $price_modifiers, $booking_info);

    $price_calendar = new UnitPricingCalendar($unit->unit_id, $price_modifiers);

    $temp_end_date = clone($end_date);
    $temp_end_date->sub(new DateInterval('P1D'));

    $price = $price_calendar->calculatePrice($start_date, $temp_end_date, $adults, $children, $childrens_age);

    $full_price = $price['full_price'] * 100;

    $line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'] = $full_price;
    $line_item->commerce_unit_price[LANGUAGE_NONE][0]['currency_code'] = commerce_default_currency();

    foreach ($line_item->commerce_unit_price[LANGUAGE_NONE][0]['data']['components'] as $key => $component) {
      $line_item->commerce_unit_price[LANGUAGE_NONE][0]['data']['components'][$key]['price']['amount'] = $full_price / $amount * $component['price']['amount'];
    }
  }
}

/**
 * Value callback for a tours_availability_reference autocomplete element.
 *
 * Replace the unit id with a unit name.
 */
function tours_availability_reference_autocomplete_value($element, $input = FALSE, $form_state) {
  if ($input === FALSE) {
    // We're building the displayed 'default value': expand the raw unit id into
    // "unit name [unit_id:n]".
    $unit_id = $element['#default_value'];
    if (!empty($unit_id)) {
      $unit = rooms_unit_load($unit_id);
      $value = $unit->name;
      $value .= ' [unit_id:' . $unit_id . ']';
      return $value;
    }
  }
}

/**
 * Validation callback for a node_reference autocomplete element.
 */
function tours_availability_reference_autocomplete_validate($element, &$form_state, $form) {
  $field = field_widget_field($element, $form_state);
  $instance = field_widget_instance($element, $form_state);

  $value = $element['#value'];
  $unit_id = NULL;

  if (!empty($value)) {
    // Check whether we have an explicit "[unit_id:n]" input.
    preg_match('/^(?:\s*|(.*) )?\[\s*unit_id\s*:\s*(\d+)\s*\]$/', $value, $matches);
    if (!empty($matches)) {
      // Explicit nid. Check that the 'title' part matches the actual title for
      // the nid.
      list(, $title, $unit_id) = $matches;
      if (!empty($title)) {
        $unit = rooms_unit_load($unit_id);
        $real_title = $unit->name;
        if (trim($title) != trim($real_title)) {
          form_error($element, t('%name: title mismatch. Please check your selection.', array('%name' => $instance['label'])));
        }
      }
    }
    else {
      // No explicit unit_id (the submitted value was not populated by
      // autocomplete selection). Get the unit_id of a referenceable node from
      // the entered title.
      $options = array(
        'string' => $value,
        'match' => 'equals',
        'limit' => 1,
      );
      $references = tours_availability_reference_potential_references($field, $options);
      if ($references) {
        // @todo The best thing would be to present the user with an
        // additional form, allowing the user to choose between valid
        // candidates with the same title. ATM, we pick the first
        // matching candidate...
        $unit_id = key($references);
      }
      else {
        form_error($element, t('%name: unable to find a unit with that title.', array('%name' => $instance['label'])));
      }
    }
  }

  // Set the element's value as the node id that was extracted from the entered
  // input.
  form_set_value($element, $unit_id, $form_state);
}

/**
 * Implements hook_field_widget_form_alter().
 */
function tours_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['#field_name'])) {
    if ($element['#field_name'] == 'field_daily_slot' || $element['#field_name'] == 'field_private_daily_slot') {
      $ief_id = $element['#ief_id'];

      foreach ($element['entities'] as $key => $value) {
        if (is_numeric($key)) {
          if (isset($value['#entity']->unit_id) && !empty($value['#entity']->unit_id)) {
            $element['entities'][$key]['actions']['manage_availability'] = array(
              '#type' => 'submit',
              '#value' => t('Manage availability'),
              '#name' => 'ief-' . $ief_id . '-manage-availability-' . $key,
              '#limit_validation_errors' => array(),
              '#submit' => array('tours_single_day_slot_manage_availability'),
              '#ief_row_delta' => $key,
              '#unit_id' => $value['#entity']->unit_id,
            );
          }
        }
      }
    }
  }
}

function tours_single_day_slot_manage_availability($form, &$form_state) {
  $unit_id = $form_state['triggering_element']['#unit_id'];

  $form_state['redirect'] = 'admin/rooms/units/unit/' . $unit_id . '/availability';
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function tours_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'admin/rooms/units/unit/%/availability' || $root_path == 'admin/rooms/units/unit/%/pricing') {
    if (isset($router_item['page_arguments'][0]->type)) {
      if ($router_item['page_arguments'][0]->type == TOURS_SINGLE_DAY_SLOT) {
        $tour_slot = rooms_unit_load(arg(4));
        $day_tour = $tour_slot->field_day_tour['und'][0]['target_id'];

        if (rooms_unit_access('update', rooms_unit_load($day_tour))) {
          // Add a 'Back to Tour' tab that links back to the parent single day tour edit page.
          $data['tabs'][0]['output'][0]['#link']['title'] = t('Back to Tour');
          $data['tabs'][0]['output'][0]['#link']['href'] = 'admin/rooms/units/unit/' . $day_tour . '/edit';
        }
        else {
          unset($data['tabs'][0]['output'][0]);
        }

        if ($data['tabs'][0]['output'][1]['#link']['path'] == 'admin/rooms/units/unit/%/edit') {
          // Remove 'edit' tab.
          unset($data['tabs'][0]['output'][1]);
        }
      }
    }
  }
}

/**
 * Implements hook_rooms_booking_amount_before_modifiers_alter().
 */
function tours_rooms_booking_amount_before_modifiers_alter(&$price, $booking_info) {
  $unit = $booking_info['unit'];

  if ($unit->type == TOURS_PRIVATE_SINGLE_DAY_SLOT) {
    $adults = $booking_info['booking_parameters']['group_size'];

    $temp_price = '';
    $max_price = '';
    $max_people = 0;
    $diff = PHP_INT_MAX;

    if (isset($unit->field_variable_pricing['und'])) {
      foreach ($unit->field_variable_pricing['und'] as $pricing) {
        if ($adults <= $pricing['first']) {
          if (($pricing['first'] - $adults) < $diff) {
            $diff = $pricing['first'] - $adults;
            $temp_price = $pricing['second'];
          }
        }

        if ($max_people < $pricing['first']) {
          $max_people = $pricing['first'];
          $max_price = $pricing['second'];
        }
      }
    }

    if ($temp_price) {
      $price = $temp_price;
    }
    elseif ($max_price) {
      $price = $max_price;
    }
  }
}
