<?php
/**
 * @file
 * tours_faceted_search.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function tours_faceted_search_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_attributes'
  $field_bases['field_attributes'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_attributes',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'attributes',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'rooms_booking_unit_options'
  $field_bases['rooms_booking_unit_options'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'rooms_booking_unit_options',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'rooms',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'rooms_options',
  );

  return $field_bases;
}
