<?php

/**
 * @file
 */

include_once 'tours.features.inc';

/**
 * Update the tours_get_tour_types function if modifying the tour types.
 */
define ('TOURS_SINGLE_DAY', 'single_day_tour');
define ('TOURS_SINGLE_DAY_SLOT', 'single_day_tour_slot');
define ('TOURS_MULTI_DAY', 'multi_day_tour');


/**
 * Drupal hooks.
 */

/**
 * Implements hook_menu().
 */
function tours_menu() {
  $items['tours_availability_reference/autocomplete/%/%/%'] = array(
    'page callback' => 'tours_availability_reference_autocomplete',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('reference booking unit availability'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function tours_theme() {
  return array(
    'tours_availability_field_calendar' => array(
      'render element' => 'tours_availability_field_calendar',
      'template' => 'tours_availability_field_calendar',
    ),
  );
}

/**
 * Implements hook_field_info().
 */
function tours_field_info() {
  return array(
    'tours_availability_reference' => array(
      'label' => t('Tours Availability Reference'),
      'description' => t('Display availability information embedded from other fieldable content.'),
      'settings' => array(
        'referenceable_unit_types' => array(),
      ),
      'default_widget' => 'tours_availability_reference_autocomplete',
      'default_formatter' => 'tours_availability_reference_default',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function tours_field_is_empty($item, $field) {
  return empty($item['unit_id']);
}

/**
 * Implements hook_field_formatter_info().
 */
function tours_field_formatter_info() {
  $ret = array(
    'tours_availability_reference_default' => array(
      'label' => t('Tours Availability Calendar'),
      'description' => t('Displays availability information on a calendar.'),
      'field types' => array('tours_availability_reference', 'entityreference'),
      'settings' => array('book_now' => '1', 'enquire_about' => '1'),
    ),
  );
  return $ret;
}

/**
 * Implements hook_field_formatter_prepare_view().
 */
function tours_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {
  if ($field['type'] == 'entityreference') {
    entityreference_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items, $displays);
  }
}

/**
 * Implements hook_field_formatter_view().
 *
 * @todo parametrize date range
 */
function tours_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $booking_ids = array();
  $element = array();

  switch ($display['type']) {
    case 'tours_availability_reference_default':

      $unit_names = array();
      $unit_ids = array();
      foreach ($items as $delta => $item) {
        if ($field['type'] == 'entityreference') {
          if (empty($item['access'])) {
            continue;
          }
          $unit = ($item['entity']);
        }
        else {
          $unit = rooms_unit_load($item['unit_id']);
        }

        if ($unit) {
          $unit_names[] = $unit->name;
          $unit_ids[] = $unit->unit_id;
        }
      }

      foreach ($unit_ids as $unit_id) {
        $booking_ids = rooms_booking_ids(array('unit_id' => $unit_id));
      }

    break;
  }

  if (!empty($booking_ids)) {
    $results = array();

    $bookings = rooms_booking_load_multiple(array_keys($booking_ids), array('type' => 'tour_instance'));

    $currency_setting = commerce_currency_load(commerce_default_currency());
    $currency_symbol = $currency_setting['symbol'];

    foreach ($bookings as $booking) {
      $results[] = array(
        'id' => $booking->booking_id,
        'start_date' => $booking->start_date_object->format('Y-m-d'),
        'end_date' => $booking->end_date_object->format('Y-m-d'),
        'price' => t('@currency_symbol @amount', array('@currency_symbol' => $currency_symbol, '@amount' => number_format($booking->price / 100, 2, '.', ''))),
        'book_now' => drupal_get_form('tours_book_now_form', $booking),
        'settings' => $display['settings'],
      );
    }

    if (!empty($results)) {
      $element[] = array(
        '#theme' => 'tours_availability_field_calendar',
        'bookings' => $results,
      );
    }
  }

  return $element;
}

/**
 * Implements hook_field_settings_form().
 */
function tours_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];

  $form = array();
  $form['referenceable_unit_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Unit types that can be referenced'),
    '#multiple' => TRUE,
    '#default_value' => isset($settings['referenceable_unit_types']) ? $settings['referenceable_unit_types'] : array(),
    '#options' => array_map('check_plain', rooms_unit_types_ids()),
  );

  return $form;

}

/**
 * Implements hook_field_validate().
 */
function tours_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Extract unit ids to check.
  $ids = array();

  // Check for non-numeric values.
  // First check non-numeric "nid's to avoid losing time with them.
  foreach ($items as $delta => $item) {
    if (is_array($item) && !empty($item['unit_id'])) {
      if (is_numeric($item['unit_id'])) {
        $ids[] = $item['unit_id'];
      }
      else {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'invalid_unit_id',
          'message' => t('%name: invalid input.',
            array('%name' => $instance['label'])),
        );
      }
    }
  }
}

/**
 * Implements hook_field_widget_info().
 */
function tours_field_widget_info() {
  return array(
    'tours_availability_reference_autocomplete' => array(
      'label'       => t('Autocomplete text field'),
      'description' => t('Display the list of referenceable units as a textfield with autocomplete behaviour.'),
      'field types' => array('tours_availability_reference'),
      'settings'    => array(
        'autocomplete_match' => 'contains',
        'size' => 60,
        'autocomplete_path' => 'tours_availability_reference/autocomplete',
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function tours_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'tours_availability_reference_autocomplete':
      $element += array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['unit_id']) ? $items[$delta]['unit_id'] : NULL,
        '#autocomplete_path' => $instance['widget']['settings']['autocomplete_path'] . '/' . $instance['entity_type'] . '/' . $instance['bundle'] . '/' . $field['field_name'],
        '#size' => $instance['widget']['settings']['size'],
        '#maxlength' => 255,
        '#element_validate' => array('tours_availability_reference_autocomplete_validate'),
        '#value_callback' => 'tours_availability_reference_autocomplete_value',
      );
      break;
  }
  return array('unit_id' => $element);
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function tours_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element['book_now'] = array(
    '#title' => t('Display "Book now"'),
    '#type' => 'checkbox',
    '#default_value' => $settings['book_now'],
  );

  $element['enquire_about'] = array(
    '#title' => t('Display "Enquire about this Tour"'),
    '#type' => 'checkbox',
    '#default_value' => $settings['enquire_about'],
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function tours_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  $summary[] = ($settings['book_now']) ? 'Display "Book now"' : 'Don\'t display "Book now"';
  $summary[] = ($settings['enquire_about']) ? 'Display "Enquire about this Tour"' : 'Don\'t display "Enquire about this Tour"';

  return implode('<br />', $summary);
}

/**
 * Value callback for a tours_availability_reference autocomplete element.
 *
 * Replace the unit id with a unit name.
 */
function tours_availability_reference_autocomplete_value($element, $input = FALSE, $form_state) {
  if ($input === FALSE) {
    // We're building the displayed 'default value': expand the raw unit id into
    // "unit name [unit_id:n]".
    $unit_id = $element['#default_value'];
    if (!empty($unit_id)) {
      $unit = rooms_unit_load($unit_id);
      $value = $unit->name;
      $value .= ' [unit_id:' . $unit_id . ']';
      return $value;
    }
  }
}

/**
 * Validation callback for a node_reference autocomplete element.
 */
function tours_availability_reference_autocomplete_validate($element, &$form_state, $form) {
  $field = field_widget_field($element, $form_state);
  $instance = field_widget_instance($element, $form_state);

  $value = $element['#value'];
  $unit_id = NULL;

  if (!empty($value)) {
    // Check whether we have an explicit "[unit_id:n]" input.
    preg_match('/^(?:\s*|(.*) )?\[\s*unit_id\s*:\s*(\d+)\s*\]$/', $value, $matches);
    if (!empty($matches)) {
      // Explicit nid. Check that the 'title' part matches the actual title for
      // the nid.
      list(, $title, $unit_id) = $matches;
      if (!empty($title)) {
        $unit = rooms_unit_load($unit_id);
        $real_title = $unit->name;
        if (trim($title) != trim($real_title)) {
          form_error($element, t('%name: title mismatch. Please check your selection.', array('%name' => $instance['label'])));
        }
      }
    }
    else {
      // No explicit unit_id (the submitted value was not populated by
      // autocomplete selection). Get the unit_id of a referenceable node from
      // the entered title.
      $options = array(
        'string' => $value,
        'match' => 'equals',
        'limit' => 1,
      );
      $references = tours_availability_reference_potential_references($field, $options);
      if ($references) {
        // @todo The best thing would be to present the user with an
        // additional form, allowing the user to choose between valid
        // candidates with the same title. ATM, we pick the first
        // matching candidate...
        $unit_id = key($references);
      }
      else {
        form_error($element, t('%name: unable to find a unit with that title.', array('%name' => $instance['label'])));
      }
    }
  }

  // Set the element's value as the node id that was extracted from the entered
  // input.
  form_set_value($element, $unit_id, $form_state);
}

/**
 * Implements hook_field_widget_error().
 */
function tours_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element['unit_id'], $error['message']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_type_form
 */
function tours_form_rooms_unit_type_form_alter(&$form, &$form_state, $form_id) {
  $unit_type = $form_state['rooms_unit_type'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_edit_form_alter
 */
function tours_form_rooms_unit_edit_form_alter(&$form, &$form_state, $form_id){
  $tour_types = tours_get_tour_types();

  if (in_array($form['#entity']->type, $tour_types)) {
    // Change Unit Name to Tour Name.
    $form['name']['#title'] = t('Tour Name');

    // Base price represents the default price for the tour.
    $form['base_price']['#title'] = t('Tour Standard Price');

    // Guest capacity is going to stand in for Tour Capacity
    $form['guest_capacity']['#title'] = t('Tour Capacity');
    $form['guest_capacity']['max_sleeps']['#description'] =
      t('The total number of people that can participate in the tour. The minimum
       number represents the minimum amount required for the tour to take place');

    // Hide chidren and bed arrangement stuff.
    unset($form['data']['bed_arrangement']);
    unset($form['child_capacity']);
  }
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * Override the availability form to make sense for tours.
 */
function tours_form_update_availability_calendar_form_alter(&$form, &$form_state, $form_id) {
  $unit = rooms_unit_load($form['rooms_update_availability']['unit_id']['#value']);
  $tour_types = tours_get_tour_types();
  if (in_array($unit->type, $tour_types)) {
    unset($form['#validate']);
    $form['rooms_update_availability']['actions']['submit']['#value'] = t('Add Instances');
    $form['rooms_update_availability']['actions']['submit']['#submit'][0] = 'tours_add_instances_form_submit';
    $form['rooms_update_availability']['#description'] = t('Enter tour dates/times.');
    unset($form['rooms_update_availability']['rooms_date_range']);
    unset($form['rooms_update_availability']['unit_state']);
    $form['rooms_update_availability']['date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d H:i',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('Starting date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );
    $form['rooms_update_availability']['end_date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d H:i',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('End date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );
    $form['rooms_update_availability']['date']['show_repeat_settings'] = array(
      '#type' => 'hidden',
      '#value' => 1,
    );
    $form['rooms_update_availability']['parent1'] = array(
      '#tree' => TRUE,
      'parent2' => array(
        '#tree' => TRUE,
        '#required' => TRUE,
        'rrule' => array(
          '#type' => 'date_repeat_rrule',
          '#theme_wrappers' => array('date_repeat_rrule'),
          '#default_value' => isset($instance->repeat_rule) ? $instance->repeat_rule : '',
          '#date_timezone' => date_default_timezone(),
          '#date_label_position' => 'above',
          '#date_format' => 'm/d/Y - H:i',
          '#date_increment' => 1,
          // '#weight' => -9,
          '#date_year_range' => '-0:+1',
          // '#date_repeat_widget' => 'date_popup_repeat',
          '#date_repeat_widget' => 'date_popup',
          '#date_flexible' => 0,
          '#date_repeat_collapsed' => TRUE,
        ),
      ),
    );
  }
}

/**
 * Validation for tour instance repeating date add form.
 */
function tours_add_instances_form_submit($form, &$form_state) {
  global $user;

  // Set up variables.
  $rrule = $form_state['values']['parent1']['parent2']['rrule'];
  $rrule_values = date_ical_parse_rrule(NULL, $rrule);
  $timezone = date_default_timezone();
  $format = 'Y-m-d H:i';
  $start_date = $form_state['values']['date'];
  $end_date = $form_state['values']['end_date'];

  // Calculate the event duration.
  $start = new DateObject($start_date, $timezone, $format);
  $end = new DateObject($end_date, $timezone, $format);
  $duration = $start->difference($end);

  // Figure out when to stop.
  $start_datetime = date_format($start, DATE_FORMAT_DATETIME);
  if (!empty($rrule_values['UNTIL']['datetime'])) {
    $end = date_ical_date($rrule_values['UNTIL'], $timezone);
    $end_datetime = date_format($end, DATE_FORMAT_DATETIME);
  }
  elseif (!empty($rrule_values['COUNT'])) {
    $end_datetime = NULL;
  }

  // Split the RRULE into RRULE, EXDATE, and RDATE parts.
  $parts = date_repeat_split_rrule($rrule);
  $parsed_exceptions = (array) $parts[1];
  $exceptions = array();
  foreach ($parsed_exceptions as $exception) {
    $date = date_ical_date($exception, $timezone);
    $exceptions[] = date_format($date, 'Y-m-d');
  }

  $parsed_rdates = (array) $parts[2];
  $additions = array();
  foreach ($parsed_rdates as $rdate) {
    $date = date_ical_date($rdate, $timezone);
    $additions[] = date_format($date, 'Y-m-d');
  }

  // Calculate the dates for bookings we want to add.
  $dates = date_repeat_calc($rrule, $start_datetime, $end_datetime, $exceptions, $timezone, $additions);
  $value = array();
  foreach ($dates as $delta => $date) {
    // date_repeat_calc always returns DATE_DATETIME dates, which is
    // not necessarily $field['type'] dates.
    // Convert returned dates back to db timezone before storing.
    $date_start = new DateObject($date, $timezone, DATE_FORMAT_DATETIME);
    $date_end = clone($date_start);
    date_modify($date_end, '+' . $duration . ' seconds');
    $value[$delta] = array(
      'value' => date_format($date_start, $format),
      'value2' => date_format($date_end, $format),
      'offset' => date_offset_get($date_start),
      'offset2' => date_offset_get($date_end),
      'timezone' => $timezone,
      'rrule' => $rrule,
      );
  }

  // Add the tour instance bookings.
  $unit = rooms_unit_load($form_state['values']['unit_id']);
  foreach ($value as $instance) {
    $profile = tours_get_default_customer_profile();

    $params = array(
      'unit_id' => $unit->unit_id,
      'unit_type' => $unit->type,
      'uid' => $user->uid,
      'customer_id' => $profile->uid,
      'name' => $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'],
      'type' => 'tour_instance',
      'created' => time(),
      'changed' => time(),
      'language' => LANGUAGE_NONE,
      'start_date' => $instance['value'],
      'end_date' => $instance['value2'],
      'data' => array('group_size' => 0),
    );
    $booking = rooms_booking_create($params);
    rooms_booking_save($booking);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modifications to tour booking form.
 */
function tours_form_rooms_booking_edit_form_alter(&$form, &$form_state) {
  if ($form['#bundle'] == 'tour_instance') {
    // Allow single day bookings.
    $form_state['single_day_bookings'] = TRUE;

    // Hide 'children' selection.
    $form['data']['group_size_children']['#access'] = FALSE;
    $form['data']['group_size_children']['#access'] = FALSE;

    $profile = tours_get_default_customer_profile();
    $form['client']['#default_value'] = $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] . ':' . $profile->profile_id;
  }
}

/**
 * Implements hook_menu_alter().
 */
function tours_menu_alter(&$items) {
  $items['admin/rooms/units/unit/%rooms_unit/availability']['page callback'] = 'tours_availability_page';
}

function tours_entity_info_alter(&$entity_info) {
  $entity_info['rooms_unit']['inline entity form'] = array(
    'controller' => 'RoomsUnitInlineEntityFormController',
  );
}

/**
 * When an entity of type tour is saved let's make sure that the tour dates
 * are set as available.
 *
 * Implements hook_entity_insert
 */
function tours_entity_insert($entity, $type) {
}

/**
 * Implements hook_entity_update
 */
function tours_entity_update($entity, $type) {
}

/**
 * Implements hook_views_default_views_alter().
 */
function tours_views_default_views_alter(&$views) {
  if (isset($views['bookings'])) {
    $views['bookings']->disabled = TRUE;
  }
}


/**
 * Commerce hooks.
 */

/**
 * Implements hook_commerce_line_item_type_info().
 */
function tours_commerce_line_item_type_info() {
  return array(
    'tours_booking' => array(
      'name' => t('Tours Booking'),
      'description' => t('Represents a booking of a Rooms Tour product.'),
      'product' => TRUE,
      'add_form_submit_value' => t('Add product'),
      'base' => 'tours_line_item',
    ),
  );
}

/**
 * Ensures the booking line item type contains a product reference field and
 * all other rooms fields required for a booking.
 *
 * @param array $line_item_type
 *   The line item type object.
 */
function tours_line_item_configuration($line_item_type) {
  $type = $line_item_type['type'];

  // Get the info about the fields and instances we need to create.
  module_load_include('inc', 'tours', 'includes/tours.fields');
  $field_data = _tours_line_item_type_fields();

  // Create the product reference field for the line item type.
  commerce_product_line_item_configuration($line_item_type);

  // For each field, check whether it already exists create it if it doesn't
  foreach ($field_data['fields'] as $field_name => $field_info) {
    $field = field_info_field($field_name);
    $instance = field_info_instance('commerce_line_item', $field_name, $type);

    if (empty($field)) {
      field_create_field($field_data['fields'][$field_name]);
    }
    if (empty($instance)) {
      field_create_instance($field_data['instances'][$field_name]);
    }
  }
}

/**
 * Implements hook_line_item_title().
 */
function tours_line_item_title($line_item) {
  // Use the line item's label for the title.
  return ($line_item->line_item_label);
}


/**
 * Rooms hooks.
 */

/**
 * Implements hook_rooms_price_modifier_alter().
 */
function tours_rooms_price_modifier_alter(&$price_modifiers, $booking_info) {
  $tour_types = tours_get_tour_types();

  // If this is a tour, modify the pricing to be per user, for the entire
  // booking period.
  if (in_array($booking_info['unit']->type, $tour_types)) {
    $length = $booking_info['end_date']->diff($booking_info['start_date']);
    $days = $length->days;
    if ($days > 1) {
      // If the tour is more than 1 day long, adjust the
      // total price to the base price.
      $price_modifiers['total'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_SUB,
        '#amount' => $booking_info['unit']->base_price,
        '#quantity' => ($days - 1),
      );
    }

    // Figure out the group size.
    if (isset($booking_info['booking_parameters']['group_size'])) {
      $group_size = $booking_info['booking_parameters']['group_size'];
    }
    elseif (isset($booking_info['booking_parameters'][0]['adults'])) {
      $group_size = $booking_info['booking_parameters'][0]['adults'];
    }
    else {
      $group_size = $booking_info['booking_parameters']['adults'];
    }

    // Add the base price for each additional person.
    if ($group_size > 1) {
      $amount_per_additional_person = $booking_info['unit']->base_price;
      $price_modifiers['additional'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_ADD,
        '#amount' => $amount_per_additional_person,
        '#quantity' => ($group_size - 1),
      );
    }
  }
}


/**
 * Custom functions.
 */


/**
 * Set a default customer if not already present.
 */
function tours_get_default_customer_profile() {
  // Look for a customer profile for the site admin.
  $profile_id = db_select('commerce_customer_profile', 'cc')
    ->fields('cc', array('profile_id'))
    ->condition('uid', 1)
    ->range(0,1)
    ->execute()
    ->fetchField();
  if ($profile_id) {
    $profile = commerce_customer_profile_load($profile_id);
  }
  else {
    // If there's not one already existing, create it.
    $profile = commerce_customer_profile_new($type = 'billing', $uid = 1);
    $profile->status = '1';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['country'] = 'US';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['administrative_area'] = 'NM';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['postal_code'] = '87501';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['locality'] = 'Santa Fe';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['thoroughfare'] = '804 Don Gaspar';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] = 'Tours Owner';
    commerce_customer_profile_save($profile);
  }
  return($profile);
}

/**
 *
 */
function tours_set_tour_dates($entity) {
  $start_date = null;
  $end_date = null;

  // Check whether start and end dates are set.
  if (isset($entity->field_tour_dates[LANGUAGE_NONE][0]['value'])) {
    $start_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value']);
    $end_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value2']);
  }

  if (!isset($start_date)) {
    drupal_set_message(t('Tour dates have not been set'));
    return FALSE;
  } else {
    $tour_event = new BookingEvent($entity->unit_id, ROOMS_AVAILABLE, $start_date, $end_date);
    dpm($tour_event);
    $events = array($tour_event);
    $ac = new UnitCalendar($entity->unit_id);
    $ac->updateCalendar($events);
  }


  dpm($start_date);
  dpm($end_date);
  return TRUE;
  // Get the tour dates from the entity
  //$start_date = $entity->field_tour_dates[LANGUAGE_NONE]
}

/**
 * Tour availability callback page
 *
 * @param \RoomsUnit $rooms_unit
 * @param string $year
 * @param string $month
 * @return array
 */
function tours_availability_page(RoomsUnit $rooms_unit, $year = '', $month = '') {
  if (in_array($rooms_unit->type, tours_get_tour_types(TRUE))) {
    // Set the page title.
    drupal_set_title(t('Edit @unit_name Tour Dates', array('@unit_name' => $rooms_unit->name)));

    // Add styles.
    rooms_availability_modal_style();

    list($url) = explode('/' . $year . '/' . $month, current_path());

    return array(
      '#theme' => 'rooms_three_month_calendar',
      '#url' => $url,
      '#form' => drupal_get_form('update_availability_calendar_form', $rooms_unit->unit_id, $year, $month),
      '#year' => $year,
      '#month' => $month,
      '#attached' => array(
        'css' => array(
          drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css',
        ),
        'js' => array(
          drupal_get_path('module', 'rooms_availability') . '/js/rooms_availability.js',
          array(
            'data' => array('roomsAvailability' => array('roomID' => $rooms_unit->unit_id)),
            'type' => 'setting',
          ),
        ),
      ),
    );

  }
  else {
    return rooms_availability_page($rooms_unit, $year, $month);
  }
}

/**
 * Return all tour types.
 * @param boolean $all
 */
function tours_get_tour_types($all = FALSE) {
  // Typically we are interested in the multi_day + single day tours, not the single day slots
  if ($all) {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY, TOURS_SINGLE_DAY_SLOT);
  } else {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY);
  }
}

/**
 * Menu callback for the autocomplete results.
 */
function tours_availability_reference_autocomplete($entity_type, $bundle, $field_name, $string = '') {
  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  $options = array(
    'string' => $string,
    'match' => $instance['widget']['settings']['autocomplete_match'],
    'limit' => 10,
  );
  $references = tours_availability_reference_potential_references($field, $options);

  $matches = array();
  foreach ($references as $id => $row) {
    // Markup is fine in autocompletion results (might happen when rendered
    // through Views) but we want to remove hyperlinks.
    $suggestion = preg_replace('/<a href="([^<]*)">([^<]*)<\/a>/', '$2', $row['rendered']);
    // Add a class wrapper for a few required CSS overrides.
    $matches[$row['title'] . " [unit_id:$id]"] = '<div class="reference-autocomplete">' . $suggestion . '</div>';
  }

  drupal_json_output($matches);
}

/**
 * Retrieves an array of candidate referenceable booking units.
 *
 * This info is used in various places (allowed values, autocomplete
 * results, input validation...). Some of them only need the nids,
 * others nid + titles, others yet nid + titles + rendered row (for
 * display in widgets).
 *
 * The array we return contains all the potentially needed information,
 * and lets consumers use the parts they actually need.
 *
 * @param array $field
 *   The field definition.
 * @param array $options
 *   An array of options to limit the scope of the returned list. The following
 *   key/value pairs are accepted:
 *   - string: string to filter unit names on (used by autocomplete).
 *   - match: operator to match the above string against, can be any of:
 *     'contains', 'equals', 'starts_with'. Defaults to 'contains'.
 *   - ids: array of specific unit ids to lookup.
 *   - limit: maximum size of the the result set. Defaults to 0 (no limit).
 *
 * @return array
 *   An array of valid units in the form:
 *   array(
 *     unit_id => array(
 *       'name' => The unit title,
 *       'rendered' => The text to display in widgets (can be HTML)
 *     ),
 *     ...
 *   )
 */
function tours_availability_reference_potential_references($field, $options = array()) {
  // Fill in default options.
  $options += array(
    'string' => '',
    'match' => 'contains',
    'ids' => array(),
    'limit' => 0,
  );

  $results = &drupal_static(__FUNCTION__, array());

  // Create unique id for static cache.
  $cid = $field['field_name'] . ':' . $options['match'] . ':'
    . ($options['string'] !== '' ? $options['string'] : implode('-', $options['ids']))
    . ':' . $options['limit'];
  if (!isset($results[$cid])) {
    $references = FALSE;

    if ($references === FALSE) {
      $references = _tours_availability_reference_potential_references($field, $options);
    }

    // Store the results.
    $results[$cid] = !empty($references) ? $references : array();
  }

  return $results[$cid];
}

/**
 * Helper function for node_reference_potential_references().
 *
 * List of referenceable nodes defined by content types.
 */
function _tours_availability_reference_potential_references($field, $options) {
  // Avoid useless work.
  if (!isset($field['settings']['referenceable_unit_types'])) {
    return array();
  }

  if (!count($field['settings']['referenceable_unit_types'])) {
    return array();
  }

  $query = db_select('rooms_units', 'u');
  $unit_unit_id_alias = $query->addField('u', 'unit_id');
  $unit_name_alias = $query->addField('u', 'name', 'name');
  $unit_type_alias = $query->addField('u', 'type', 'type');

  if (is_array($field['settings']['referenceable_unit_types'])) {
    $query->condition('u.type', $field['settings']['referenceable_unit_types'], 'IN');
  }

  if ($options['string'] !== '') {
    switch ($options['match']) {
      case 'contains':
        $query->condition('u.name', '%' . $options['string'] . '%', 'LIKE');
        break;

      case 'starts_with':
        $query->condition('u.name', $options['string'] . '%', 'LIKE');
        break;

      case 'equals':
      default:
        // No match type or incorrect match type: use "=".
        $query->condition('u.name', $options['string']);
        break;
    }
  }

  if ($options['ids']) {
    $query->condition('u.unit_id', $options['ids'], 'IN');
  }

  if ($options['limit']) {
    $query->range(0, $options['limit']);
  }

  $query
    ->orderBy($unit_name_alias)
    ->orderBy($unit_type_alias);

  $result = $query->execute()->fetchAll();
  $references = array();
  foreach ($result as $unit) {
    $references[$unit->unit_id] = array(
      'title'    => $unit->name,
      'rendered' => check_plain($unit->name),
    );
  }
  return $references;
}

function tours_book_now_form($form, &$form_state, $booking) {
  $form['booking_id'] = array(
    '#type' => 'hidden',
    '#value' => $booking->booking_id,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Book Now'),
  );

  return $form;
}

function tours_book_now_form_submit($form, &$form_state) {
  module_load_include('inc', 'tours', 'tours.commerce');

  global $user;

  $order = commerce_order_new($user->uid, 'pending');
  commerce_order_save($order);

  $booking_id = $form_state['values']['booking_id'];

  $booking = rooms_booking_load($booking_id);

  $unit = array(
    'unit' => rooms_unit_load($booking->unit_id),
    'state' => ROOMS_AVAILABLE,
  );

  $sd = $booking->start_date_object;
  $ed = $booking->end_date_object;

  $booking_parameters = array('adults' => $booking->data['group_size'], 'children' => 0);

  $agent = new AvailabilityAgent($sd, $ed, $booking_parameters);

  $price_modifiers = array();

  $line_item = tours_create_line_item($unit, $agent, $booking_parameters, $price_modifiers);

  $line_item->tours_booking_reference['und'][0]['target_id'] = $booking->booking_id;

  // Add line item to cart.
  $line_item = commerce_cart_product_add($user->uid, $line_item, FALSE);

  // Refresh line items price and redirect to bookings page.
  commerce_cart_order_refresh(commerce_cart_order_load($user->uid));

  $form_state['redirect'] = 'bookings';
}

/**
 * Calculates the price for rooms_booking line item types.
 *
 * @param object $line_item
 *   Line item to modify.
 */
function tours_price_apply($line_item) {
  if ($line_item->type == 'tours_booking') {
    if ($item = field_get_items('commerce_line_item', $line_item, 'commerce_product')) {
      $product = commerce_product_load($item[0]['product_id']);
      if ($product->sku != 'ROOMS-BASIC-BOOKING') {
        return;
      }
    }
    $amount = $line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'];

    $start_date = new DateTime($line_item->tours_booking_dates[LANGUAGE_NONE][0]['value']);
    $end_date = new DateTime($line_item->tours_booking_dates[LANGUAGE_NONE][0]['value2']);

    $unit_id = $line_item->tours_booked_unit_id[LANGUAGE_NONE][0]['value'];
    $unit = rooms_unit_load($unit_id);

    // First set up price modifiers.
    $price_options = is_array(field_get_items('commerce_line_item', $line_item, 'rooms_booking_options')) ? field_get_items('commerce_line_item', $line_item, 'rooms_booking_options') : array();

    // Convert Price options in Price modifiers.
    foreach ($price_options as $option) {
      $price_modifiers[strtolower(str_replace(array(':', ' '), '_', $option['name']))] = array(
        '#name' => $option['name'],
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => $option['operation'],
        '#amount' => $option['value'],
        '#quantity' => $option['quantity'],
      );
    }

    $adults = $line_item->tours_booking_number_people[LANGUAGE_NONE][0]['value'];
    $children = $line_item->tours_booking_number_people[LANGUAGE_NONE][1]['value'];
    $childrens_age = (isset($line_item->tours_booking_children_ages[LANGUAGE_NONE])) ?
                      $line_item->tours_booking_children_ages[LANGUAGE_NONE] : array();

    $booking_info = array(
      'start_date' => clone($start_date),
      'end_date' => clone($end_date),
      'unit' => $unit,
      'booking_parameters' => array(
        'group_size' => $adults,
        'group_size_children' => $children,
        'childrens_age' => $childrens_age,
      ),
    );

    // Give other modules a chance to change the price modifiers.
    drupal_alter('rooms_price_modifier', $price_modifiers, $booking_info);

    $price_calendar = new UnitPricingCalendar($unit->unit_id, $price_modifiers);

    $temp_end_date = clone($end_date);
    $temp_end_date->sub(new DateInterval('P1D'));

    $price = $price_calendar->calculatePrice($start_date, $temp_end_date, $adults, $children, $childrens_age);

    $full_price = $price['full_price'] * 100;

    $line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'] = $full_price;
    $line_item->commerce_unit_price[LANGUAGE_NONE][0]['currency_code'] = commerce_default_currency();

    foreach ($line_item->commerce_unit_price[LANGUAGE_NONE][0]['data']['components'] as $key => $component) {
      $line_item->commerce_unit_price[LANGUAGE_NONE][0]['data']['components'][$key]['price']['amount'] = $full_price / $amount * $component['price']['amount'];
    }
  }
}

/**
 * Implements hook_default_rules_configuration_alter().
 */
function tours_default_rules_configuration_alter(&$configs) {
  if (isset($configs['rooms'])) {
    $configs['rooms']->action('tours_price_apply', array('#_needs_processing' => TRUE, 'commerce_line_item:select' => 'commerce-line-item'));
  }
}

/**
 * Implements hook_commerce_checkout_complete().
 */
function tours_commerce_checkout_complete($order) {
  foreach ($order->commerce_line_items as $lang => $item) {
    foreach ($item as $item_id) {
      $line_item = commerce_line_item_load($item_id['line_item_id']);
      if ($line_item->type == 'tours_booking') {
        $booking = rooms_booking_load($line_item->tours_booking_reference['und'][0]['target_id']);

        $booking->field_tour_orders['und'][0]['target_id'] = $order->order_id;

        rooms_booking_save($booking);
      }
    }
  }
}
