<?php

/**
 * @file
 */

include_once 'tours.features.inc';

/**
 * Update the tours_get_tour_types function if modifying the tour types.
 */
define ('TOURS_SINGLE_DAY', 'single_day_tour');
define ('TOURS_SINGLE_DAY_SLOT', 'single_day_tour_slot');
define ('TOURS_MULTI_DAY', 'multi_day_tour');


/**
 * Drupal hooks.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_availability_event_manager_form
 */
function tours_form_rooms_availability_event_manager_form_alter(&$form, $form_state) {
  $unit = rooms_unit_load($form['unit_id']['#value']);
  $tour_types = tours_get_tour_types();

  if (in_array($unit->type, $tour_types)) {
    // This is a tours unit, hide the standard booking link.
    if (isset($form['order']['order_link']['standard_booking'])) {
      unset($form['order']['order_link']['standard_booking']);
    }
  }
  else {
    // This is not a tours unit, hide the tours booking link.
    if (isset($form['order']['order_link']['tour_instance'])) {
      unset($form['order']['order_link']['tour_instance']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_type_form
 */
function tours_form_rooms_unit_type_form_alter(&$form, &$form_state, $form_id) {
  $unit_type = $form_state['rooms_unit_type'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = rooms_unit_edit_form_alter
 */
function tours_form_rooms_unit_edit_form_alter(&$form, &$form_state, $form_id){
  $tour_types = tours_get_tour_types();

  if (in_array($form['#entity']->type, $tour_types)) {
    // Change Unit Name to Tour Name.
    $form['name']['#title'] = t('Tour Name');

    // Base price represents the default price for the tour.
    $form['base_price']['#title'] = t('Tour Standard Price');

    // Guest capacity is going to stand in for Tour Capacity
    $form['guest_capacity']['#title'] = t('Tour Capacity');
    $form['guest_capacity']['max_sleeps']['#description'] =
      t('The total number of people that can participate in the tour. The minimum
       number represents the minimum amount required for the tour to take place');

    // Hide chidren and bed arrangement stuff.
    unset($form['data']['bed_arrangement']);
    unset($form['child_capacity']);

    // Hide option to create multiple units.
    $form['multi']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * Override the availability form to make sense for tours.
 */
function tours_form_update_availability_calendar_form_alter(&$form, &$form_state, $form_id) {
  $unit = rooms_unit_load($form['rooms_update_availability']['unit_id']['#value']);
  $tour_types = tours_get_tour_types();
  if (in_array($unit->type, $tour_types)) {
    unset($form['#validate']);
    $form['rooms_update_availability']['actions']['submit']['#value'] = t('Add Instances');
    $form['rooms_update_availability']['actions']['submit']['#submit'][0] = 'tours_add_instances_form_submit';
    $form['rooms_update_availability']['#description'] = t('Enter tour dates/times.');
    unset($form['rooms_update_availability']['rooms_date_range']);
    unset($form['rooms_update_availability']['unit_state']);
    $form['rooms_update_availability']['date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d H:i',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('Starting date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );
    $form['rooms_update_availability']['end_date'] = array(
      '#type' => 'date_popup',
      '#required' => TRUE,
      '#date_timezone' => date_default_timezone(),
      '#date_increment' => 2,
      '#date_format' => 'Y-m-d H:i',
      '#date_year_range' => '-0:+1',
      '#date_type' => DATE_DATETIME,
      '#title' => t('End date'),
      '#default_value' => '',
      '#required' => TRUE,
      '#element_validate' => array(
        'date_repeat_field_widget_validate',
      ),
      '#field_name' => 'field_not_really_a_field',
      '#field_parents' => array('dates'),
      '#entity_type' => 'booking',
      '#bundle' => 'tour_instance',
      '#date_is_default' => TRUE,
      '#language' => LANGUAGE_NONE,
    );
    $form['rooms_update_availability']['date']['show_repeat_settings'] = array(
      '#type' => 'hidden',
      '#value' => 1,
    );
    $form['rooms_update_availability']['parent1'] = array(
      '#tree' => TRUE,
      'parent2' => array(
        '#tree' => TRUE,
        '#required' => TRUE,
        'rrule' => array(
          '#type' => 'date_repeat_rrule',
          '#theme_wrappers' => array('date_repeat_rrule'),
          '#default_value' => isset($instance->repeat_rule) ? $instance->repeat_rule : '',
          '#date_timezone' => date_default_timezone(),
          '#date_label_position' => 'above',
          '#date_format' => 'm/d/Y - H:i',
          '#date_increment' => 1,
          // '#weight' => -9,
          '#date_year_range' => '-0:+1',
          // '#date_repeat_widget' => 'date_popup_repeat',
          '#date_repeat_widget' => 'date_popup',
          '#date_flexible' => 0,
          '#date_repeat_collapsed' => TRUE,
        ),
      ),
    );
  }
}

/**
 * Validation for tour instance repeating date add form.
 */
function tours_add_instances_form_submit($form, &$form_state) {
  global $user;

  // Set up variables.
  $rrule = $form_state['values']['parent1']['parent2']['rrule'];
  $rrule_values = date_ical_parse_rrule(NULL, $rrule);
  $timezone = date_default_timezone();
  $format = 'Y-m-d H:i';
  $start_date = $form_state['values']['date'];
  $end_date = $form_state['values']['end_date'];

  // Calculate the event duration.
  $start = new DateObject($start_date, $timezone, $format);
  $end = new DateObject($end_date, $timezone, $format);
  $duration = $start->difference($end);

  // Figure out when to stop.
  $start_datetime = date_format($start, DATE_FORMAT_DATETIME);
  if (!empty($rrule_values['UNTIL']['datetime'])) {
    $end = date_ical_date($rrule_values['UNTIL'], $timezone);
    $end_datetime = date_format($end, DATE_FORMAT_DATETIME);
  }
  elseif (!empty($rrule_values['COUNT'])) {
    $end_datetime = NULL;
  }

  // Split the RRULE into RRULE, EXDATE, and RDATE parts.
  $parts = date_repeat_split_rrule($rrule);
  $parsed_exceptions = (array) $parts[1];
  $exceptions = array();
  foreach ($parsed_exceptions as $exception) {
    $date = date_ical_date($exception, $timezone);
    $exceptions[] = date_format($date, 'Y-m-d');
  }

  $parsed_rdates = (array) $parts[2];
  $additions = array();
  foreach ($parsed_rdates as $rdate) {
    $date = date_ical_date($rdate, $timezone);
    $additions[] = date_format($date, 'Y-m-d');
  }

  // Calculate the dates for bookings we want to add.
  $dates = date_repeat_calc($rrule, $start_datetime, $end_datetime, $exceptions, $timezone, $additions);
  $value = array();
  foreach ($dates as $delta => $date) {
    // date_repeat_calc always returns DATE_DATETIME dates, which is
    // not necessarily $field['type'] dates.
    // Convert returned dates back to db timezone before storing.
    $date_start = new DateObject($date, $timezone, DATE_FORMAT_DATETIME);
    $date_end = clone($date_start);
    date_modify($date_end, '+' . $duration . ' seconds');
    $value[$delta] = array(
      'value' => date_format($date_start, $format),
      'value2' => date_format($date_end, $format),
      'offset' => date_offset_get($date_start),
      'offset2' => date_offset_get($date_end),
      'timezone' => $timezone,
      'rrule' => $rrule,
      );
  }

  // Add the tour instance bookings.
  $unit = rooms_unit_load($form_state['values']['unit_id']);
  foreach ($value as $instance) {
    $profile = tours_get_default_customer_profile();

    $params = array(
      'unit_id' => $unit->unit_id,
      'unit_type' => $unit->type,
      'uid' => $user->uid,
      'customer_id' => $profile->uid,
      'name' => $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'],
      'type' => 'tour_instance',
      'created' => time(),
      'changed' => time(),
      'language' => LANGUAGE_NONE,
      'start_date' => $instance['value'],
      'end_date' => $instance['value2'],
      'data' => array('group_size' => 0),
    );
    $booking = rooms_booking_create($params);
    rooms_booking_save($booking);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modifications to tour booking form.
 */
function tours_form_rooms_booking_edit_form_alter(&$form, &$form_state) {
  if ($form['#bundle'] == 'tour_instance') {
    // Allow single day bookings.
    $form_state['single_day_bookings'] = TRUE;

    // Hide 'children' selection.
    $form['data']['group_size_children']['#access'] = FALSE;
    $form['data']['group_size_children']['#access'] = FALSE;

    $profile = tours_get_default_customer_profile();
    $form['client']['#default_value'] = $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] . ':' . $profile->profile_id;
  }
}

/**
 * Implements hook_menu_alter().
 */
function tours_menu_alter(&$items) {
  $items['admin/rooms/units/unit/%rooms_unit/availability']['page callback'] = 'tours_availability_page';
}

function tours_entity_info_alter(&$entity_info) {
  $entity_info['rooms_unit']['inline entity form'] = array(
    'controller' => 'RoomsUnitInlineEntityFormController',
  );
}

/**
 * When an entity of type tour is saved let's make sure that the tour dates
 * are set as available.
 *
 * Implements hook_entity_insert
 */
function tours_entity_insert($entity, $type) {
}

/**
 * Implements hook_entity_update
 */
function tours_entity_update($entity, $type) {
}

/**
 * Implements hook_views_default_views_alter().
 */
function tours_views_default_views_alter(&$views) {
  if (isset($views['bookings'])) {
    $views['bookings']->disabled = TRUE;
  }
}


/**
 * Commerce hooks.
 */

/**
 * Implements hook_commerce_line_item_type_info().
 */
function tours_commerce_line_item_type_info() {
  return array(
    'tours_booking' => array(
      'name' => t('Tours Booking'),
      'description' => t('Represents a booking of a Rooms Tour product.'),
      'product' => TRUE,
      'add_form_submit_value' => t('Add product'),
      'base' => 'tours_line_item',
    ),
  );
}

/**
 * Ensures the booking line item type contains a product reference field and
 * all other rooms fields required for a booking.
 *
 * @param array $line_item_type
 *   The line item type object.
 */
function tours_line_item_configuration($line_item_type) {
  $type = $line_item_type['type'];

  // Get the info about the fields and instances we need to create.
  module_load_include('inc', 'tours', 'includes/tours.fields');
  $field_data = _tours_line_item_type_fields();

  // Create the product reference field for the line item type.
  commerce_product_line_item_configuration($line_item_type);

  // For each field, check whether it already exists create it if it doesn't
  foreach ($field_data['fields'] as $field_name => $field_info) {
    $field = field_info_field($field_name);
    $instance = field_info_instance('commerce_line_item', $field_name, $type);

    if (empty($field)) {
      field_create_field($field_data['fields'][$field_name]);
    }
    if (empty($instance)) {
      field_create_instance($field_data['instances'][$field_name]);
    }
  }
}

/**
 * Implements hook_line_item_title().
 */
function tours_line_item_title($line_item) {
  // Use the line item's label for the title.
  return ($line_item->line_item_label);
}


/**
 * Rooms hooks.
 */

/**
 * Implements hook_rooms_price_modifier_alter().
 */
function tours_rooms_price_modifier_alter(&$price_modifiers, $booking_info) {
  $tour_types = tours_get_tour_types();

  // If this is a tour, modify the pricing to be per user, for the entire
  // booking period.
  if (in_array($booking_info['unit']->type, $tour_types)) {
    $length = $booking_info['end_date']->diff($booking_info['start_date']);
    $days = $length->days;
    if ($days > 1) {
      // If the tour is more than 1 day long, adjust the
      // total price to the base price.
      $price_modifiers['total'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_SUB,
        '#amount' => $booking_info['unit']->base_price,
        '#quantity' => ($days - 1),
      );
    }

    // Figure out the group size.
    if (isset($booking_info['booking_parameters']['group_size'])) {
      $group_size = $booking_info['booking_parameters']['group_size'];
    }
    elseif (isset($booking_info['booking_parameters'][0]['adults'])) {
      $group_size = $booking_info['booking_parameters'][0]['adults'];
    }
    else {
      $group_size = $booking_info['booking_parameters']['adults'];
    }

    // Add the base price for each additional person.
    if ($group_size > 1) {
      $amount_per_additional_person = $booking_info['unit']->base_price;
      $price_modifiers['additional'] = array(
        '#type' => ROOMS_DYNAMIC_MODIFIER,
        '#op_type' => ROOMS_ADD,
        '#amount' => $amount_per_additional_person,
        '#quantity' => ($group_size - 1),
      );
    }
  }
}


/**
 * Custom functions.
 */


/**
 * Set a default customer if not already present.
 */
function tours_get_default_customer_profile() {
  // Look for a customer profile for the site admin.
  $profile_id = db_select('commerce_customer_profile', 'cc')
    ->fields('cc', array('profile_id'))
    ->condition('uid', 1)
    ->range(0,1)
    ->execute()
    ->fetchField();
  if ($profile_id) {
    $profile = commerce_customer_profile_load($profile_id);
  }
  else {
    // If there's not one already existing, create it.
    $profile = commerce_customer_profile_new($type = 'billing', $uid = 1);
    $profile->status = '1';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['country'] = 'US';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['administrative_area'] = 'NM';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['postal_code'] = '87501';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['locality'] = 'Santa Fe';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['thoroughfare'] = '804 Don Gaspar';
    $profile->commerce_customer_address[LANGUAGE_NONE][0]['name_line'] = 'Tours Owner';
    commerce_customer_profile_save($profile);
  }
  return($profile);
}

/**
 *
 */
function tours_set_tour_dates($entity) {
  $start_date = null;
  $end_date = null;

  // Check whether start and end dates are set.
  if (isset($entity->field_tour_dates[LANGUAGE_NONE][0]['value'])) {
    $start_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value']);
    $end_date = new DateTime($entity->field_tour_dates[LANGUAGE_NONE][0]['value2']);
  }

  if (!isset($start_date)) {
    drupal_set_message(t('Tour dates have not been set'));
    return FALSE;
  } else {
    $tour_event = new BookingEvent($entity->unit_id, ROOMS_AVAILABLE, $start_date, $end_date);
    dpm($tour_event);
    $events = array($tour_event);
    $ac = new UnitCalendar($entity->unit_id);
    $ac->updateCalendar($events);
  }


  dpm($start_date);
  dpm($end_date);
  return TRUE;
  // Get the tour dates from the entity
  //$start_date = $entity->field_tour_dates[LANGUAGE_NONE]
}

/**
 * Tour availability callback page
 *
 * @param \RoomsUnit $rooms_unit
 * @param string $year
 * @param string $month
 * @return array
 */
function tours_availability_page(RoomsUnit $rooms_unit, $year = '', $month = '') {
  if (in_array($rooms_unit->type, tours_get_tour_types(TRUE))) {
    // Set the page title.
    drupal_set_title(t('Edit @unit_name Tour Dates', array('@unit_name' => $rooms_unit->name)));

    // Add styles.
    rooms_availability_modal_style();

    list($url) = explode('/' . $year . '/' . $month, current_path());

    return array(
      '#theme' => 'rooms_three_month_calendar',
      '#url' => $url,
      '#form' => drupal_get_form('update_availability_calendar_form', $rooms_unit->unit_id, $year, $month),
      '#year' => $year,
      '#month' => $month,
      '#attached' => array(
        'css' => array(
          drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css',
        ),
        'js' => array(
          drupal_get_path('module', 'rooms_availability') . '/js/rooms_availability.js',
          array(
            'data' => array('roomsAvailability' => array('roomID' => $rooms_unit->unit_id)),
            'type' => 'setting',
          ),
        ),
      ),
    );

  }
  else {
    return rooms_availability_page($rooms_unit, $year, $month);
  }
}

/**
 * Return all tour types.
 * @param boolean $all
 */
function tours_get_tour_types($all = FALSE) {
  // Typically we are interested in the multi_day + single day tours, not the single day slots
  if ($all) {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY, TOURS_SINGLE_DAY_SLOT);
  } else {
    return array(TOURS_MULTI_DAY, TOURS_SINGLE_DAY);
  }
}
